### ISSUE TITLE
Audio Support on Acer Chromebook Spin 514s (depthboot)

### ISSUE THREAD

**Issue by DarkSystemGit** [WeirdTreeThing/chromebook-linux-audio#1]
So, the script is saying that the computer not supported, is support in the works? Or is there a way to get it working. I'd prefer to have this as my main system, but I need audio support, so yeah.

**Comment by WeirdTreeThing** [comment]
What's the board name?

**Comment by DarkSystemGit** [comment]
dewatt

**Comment by DarkSystemGit** [comment]
It's a AMD Ryzen 3 based computer

**Comment by WeirdTreeThing** [comment]
Oh, it's one of those brand new AMD Ryzen 5000 chromebooks, I'll work on making UCM for these.

**Comment by DarkSystemGit** [comment]
Thx, how long do you estamate it will take.

**Comment by WeirdTreeThing** [comment]
Very soon, can you send the output of `cat /proc/asound/cards`.

**Comment by DarkSystemGit** [comment]
I'm currently in chrome so give me like, 10 mins.

**Comment by WeirdTreeThing** [comment]
Actually, could you send the output from both ChromeOS and linux?

**Comment by DarkSystemGit** [comment]
Linux: 
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xe05c0000 irq 52

**Comment by DarkSystemGit** [comment]
Now time to go to chrome

**Comment by DarkSystemGit** [comment]
Chrome:
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xe05c0000 irq 55
 1 [sofrt5682srt101]: sof-rt5682s-rt1 - sof-rt5682s-rt1019
                      Google-Dewatt-rev4

**Comment by DarkSystemGit** [comment]
Quite diffrent, I think Linux is not picking up on the second one

**Comment by WeirdTreeThing** [comment]
Looks like there is something missing in the kernel then, but the output from ChromeOS is helpful.

**Comment by DarkSystemGit** [comment]
oh, does the kernel need to be changed or just the audio script

**Comment by WeirdTreeThing** [comment]
Both

**Comment by DarkSystemGit** [comment]
Ahhhh, do you know who makes the kernels
It's time to open another issue

**Comment by WeirdTreeThing** [comment]
I assume you are using depthboot, right? Because MrChromebox hasn't released any custom firmware for Guybrush boards yet.

**Comment by DarkSystemGit** [comment]
Yeah, I used to use chrx on my old chromebook, and it bricked it so im not going near ufei anytime soon

**Comment by WeirdTreeThing** [comment]
Well, due to how AMD's PSP team doesn't seem to care much about chromebooks, there probably won't be UEFI firmware for these boards for quite some time, though RW_LEGACY is possible and doesn't have any risk of bricking.

**Comment by WeirdTreeThing** [comment]
Anyway, go talk to Apacelus about kernels on depthboot.

**Comment by DarkSystemGit** [comment]
Ah, ok.

**Comment by DarkSystemGit** [comment]
Thanks for your help

**Comment by WeirdTreeThing** [comment]
On ChromeOS, can you run `cat /etc/modprobe.d/alsa-guybrush.conf`

**Comment by DarkSystemGit** [comment]
Result:
# Will be used for blacklisting some drivers when SOF enabled

**Comment by WeirdTreeThing** [comment]
Well, for now I'm not entirely sure how to force the use of the sof driver, but it might just default to using sof when it can.

**Comment by DarkSystemGit** [comment]
I really have no idea what youre talking about, but continue doing what youre doing, beacuse it's working so far.

**Comment by WeirdTreeThing** [comment]
@DarkSystemGit I added support for your audio card to the script, now you just need to wait for kernel support.

**Comment by DarkSystemGit** [comment]
Thanks alot, I thought I would be stuck here for weeks. Do you know what's the active repo for the kernel?

**Comment by WeirdTreeThing** [comment]
Just wait for Apacelus to respond.

**Comment by WeirdTreeThing** [comment]
@DarkSystemGit I had a look for myself and their latest dev kernel should have all the needed modules enabled, the latest release kernel is from before I left and I had disabled the modules for your card since I didn't realize that any of these new AMD chromebooks were released.

**Comment by DarkSystemGit** [comment]
oh, thx
