### ISSUE TITLE
No Audio Redrix

### ISSUE THREAD

**Issue by pacmacm** [WeirdTreeThing/chromebook-linux-audio#101]
There is only dummy output for output devices in gnome and no input devices found in gnome setting on arch linux.
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14365938/debug-logs.tar.gz)

**Boardname**
redrix

Any ideas on how I might go about fixing this?

**Comment by WeirdTreeThing** [comment]
Possibly related to #70

**Comment by pacmacm** [comment]
I tried downgrading the kernel by compiling and successfully booting linux-6.1.78(it was the closest source I could find to what they mentioned in #70 ) and rerunning setup-audio but still no luck. Here are my debug new logs: 
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14368393/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Oh right, alderlake on older kernels needs a modprobe config, see #100

**Comment by WeirdTreeThing** [comment]
Or #95 for instructions

**Comment by ChocolateLoverRaj** [comment]
I have no audio on my redrix too. I remember when I first got redrix @WeirdTreeThing did update the script and the sound and mic was working no problem. I just installed Fedora 39 and I'm running `dnf upgrade`. I'll see if that fixes the audio. Also @pacmacm how is your experience on redrix? Are you using RW_LEGACY or full rom?

**Comment by ChocolateLoverRaj** [comment]
Actually I think my issue might be from using an ipu6 kernel. I will retry with the latest fedora kernel and comment the result.

**Comment by ChocolateLoverRaj** [comment]
It still doesn't work. Info:
```
rajas@Redrix:~$ neofetch 
             .',;::::;,'.                rajas@Redrix 
         .';:cccccccccccc:;,.            ------------ 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 39 (KDE Plasma) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Redrix rev3 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.7.7-200.fc39.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 48 secs 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2102 (rpm), 8 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.26 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2256x1504 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: Plasma 5.27.10 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: kwin 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: [Plasma], Breeze [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: [Plasma], breeze-dark [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: konsole 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: 12th Gen Intel i7-1265U (12) @ 4.800GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: Intel Alder Lake-UP3 GT2 [Iris Xe Graphics] 
:cccccccccccccccccccccccccccc:'.         Memory: 3317MiB / 31934MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
rajas@Redrix:~$ cat /etc/modprobe.d/sof.conf
options snd-intel-dspcfg dsp_driver=3                                                              
```

**Comment by pacmacm** [comment]
I am very happy with redrix overall, I've been using it without the camera, mic or speakers working and still tend to use it more than my pink pixelbook go. I am using the full rom firmware. Earlier when I opened to issue I tried installing fedora just out of curiosity but still couldn't get the audio script to fix it. I looked into compiling a kernel while on Fedora but I found it was going to be a lot more difficult and didn't see any benefits to staying on fedora. I actually had a hard time installing the packages I needed from their repo so I moved back to arch and have been using it ever since.

Just now I did a system upgrade, cloned the repo and Made a file /etc/modprobe.d/sof.conf with the line options snd-intel-dspcfg dsp_driver=3 Like Weirdtreething suggested, ran the script and rebooted

[riley@archlinux ~]$ ./setup-audio
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing SOF
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1245, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 1245 (delta 141), reused 183 (delta 66), pack-reused 976
Receiving objects: 100% (1245/1245), 213.60 KiB | 354.00 KiB/s, done.
Resolving deltas: 100% (628/628), done.
Increasing alsa headroom (fixes instability)
Audio installed successfully! Reboot to finish setup.

after rebooting I am still having the same problem:

[riley@archlinux ~]$ wpctl status
PipeWire 'pipewire-0' [1.0.3, riley@archlinux, cookie:4209167127]
 └─ Clients:
        31. pipewire                            [1.0.3, riley@archlinux, pid:1778]
        33. WirePlumber                         [1.0.3, riley@archlinux, pid:1777]
        34. WirePlumber [export]                [1.0.3, riley@archlinux, pid:1777]
        46. Firefox                             [1.0.3, riley@archlinux, pid:1907]
        52. wpctl                               [1.0.3, riley@archlinux, pid:2629]

Audio
 ├─ Devices:
 │      45. Alder Lake PCH-P High Definition Audio Controller [alsa]
 │
 ├─ Sinks:
 │  *   32. Dummy Output                        [vol: 1.00]
 │
 ├─ Sink endpoints:
 │
 ├─ Sources:
 │
 ├─ Source endpoints:
 │
 └─ Streams:
        47. Firefox
             49. output_FL       > Dummy Output:playback_FL	[active]
             51. output_FR       > Dummy Output:playback_FR	[active]

Video
 ├─ Devices:
 │
 ├─ Sinks:
 │
 ├─ Sink endpoints:
 │
 ├─ Sources:
 │
 ├─ Source endpoints:
 │
 └─ Streams:

Settings
 └─ Default Configured Node Names:
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14516047/debug-logs.tar.gz)

**Comment by ChocolateLoverRaj** [comment]
@pacmacm how is suspend and battery usage while suspended on full rom? When I tried full rom suspend apparently didn't work at all in Windows 11 and it was inconsistent in Linux. Sometimes it worked, and other times it didn't, and there wasn't any way of telling because either way the power light would be white and unblinking.

**Comment by ChocolateLoverRaj** [comment]
@pacmacm do you also have issues with HDMI through Thunderbolt 4 ports?

**Comment by pacmacm** [comment]
@ChocolateLoverRaj Suspend works reasonably well. Id say that battery life is preserved as well as any other laptop ive tested. The only minor inconvinience is that when I open the lid of the laptop again the majority of the time I have to either hit a key on the keyboard or tap the trackpad to get it to come back out of suspend. 

The hdmi port works without issue on wayland. I have not yet tested hdmi through the thunderbolt 4 port.

**Comment by ChocolateLoverRaj** [comment]
When I first got installed Linux on a Redrix, @WeirdTreeThing got audio and mic to work without issues. So today, I went back to a commit from around the last time I used redrix, and **audio and mic worked today** with the script and configs from November. I created a branch as a temporary alternative for Redrix until this issue is fixed - https://github.com/ChocolateLoverRaj/chromebook-linux-audio/tree/redrix-temp. @pacmacm see if it works for you.

**Comment by pacmacm** [comment]
That worked! Thank you very much. @ChocolateLoverRaj

**Comment by WeirdTreeThing** [comment]
what exactly is the issue here

**Comment by pacmacm** [comment]
I removed to modprobe config file and rebooted to see if it would make a difference and it doesn't seem to have removed any functionality. It seems as if something has changed since this older version of the script that has broken compatibility with redrix

**Comment by WeirdTreeThing** [comment]
send logs with the modprobe config

**Comment by ChocolateLoverRaj** [comment]
Logs when audio is working or not working? I guess I will fresh install fedora on an external SSD, run your latest script, and then send logs.

**Comment by WeirdTreeThing** [comment]
not working

**Comment by ChocolateLoverRaj** [comment]
> send logs with the modprobe config

@WeirdTreeThing what command should I run for logs besides `dmesg`?

**Comment by ChocolateLoverRaj** [comment]
> send logs with the modprobe config

I'm not sure what you mean by "with the modprobe config". Here are the logs after running the script without doing anything else, on a fresh install of Fedora 39 (KDE).
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14517909/debug-logs.tar.gz)

**Comment by pacmacm** [comment]
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14517922/debug-logs.tar.gz)

Here are my current logs running Arch

**Comment by WeirdTreeThing** [comment]
Rajas update your kernel and send logs again

**Comment by WeirdTreeThing** [comment]
pacmacm is the issue that audio never actually outputs?

**Comment by WeirdTreeThing** [comment]
i have located the issue, it ended up being a skill issue

**Comment by ChocolateLoverRaj** [comment]
So I don't have to update kernel and test?

**Comment by WeirdTreeThing** [comment]
You still do

**Comment by WeirdTreeThing** [comment]
You need at least 6.6 for my patch that uses the sof driver by default on ADL/RPL. Before that, it would use the hdaudio driver which won't work on chromebooks. Alternatively you can use the modprobe config that I mentioned before to force the sof driver.

**Comment by ChocolateLoverRaj** [comment]
> You still do

Should I git pull and rerun the script after updating the kernel?

**Comment by WeirdTreeThing** [comment]
Just update your system until I tell you that I fixed the issue on my side

**Comment by ChocolateLoverRaj** [comment]
I have a new install just for testing. I already have audio working with the latest kernel on main install. Should I still update the test install and send logs? And if so, should I re run the script before sending logs?

**Comment by WeirdTreeThing** [comment]
Update your test system, wait for me to push my changes, test them and if it's still broken, send logs.

**Comment by ChocolateLoverRaj** [comment]
K, let me know when your changes are pushed.

**Comment by WeirdTreeThing** [comment]
changes have been pushed to the ucm repo

**Comment by ChocolateLoverRaj** [comment]
I tested it and the audio works now

**Comment by ChocolateLoverRaj** [comment]
@WeirdTreeThing u can close this issue now

**Comment by WeirdTreeThing** [comment]
How about I wait for OP to comment, it is their issue after all.

**Comment by pacmacm** [comment]
This all sounds good to me.  I'll do whatever I can to help solve this new suspend issue. Thanks everybody.
