### ISSUE TITLE
[Delbin] Headphone's Mic does not appear when plugged in

### ISSUE THREAD

**Issue by CoolPenguin27** [WeirdTreeThing/chromebook-linux-audio#103]
**Describe the bug**
The headphone's mic does not get registered under Linux. 
It does not appear alongside the Headphone's output and does not appear anywhere else.

**Boardname**
Delbin

**Logs**
[debug-logs(no-headset-mic).tar.gz](https://github.com/CoolPenguin27/coolpenguin27-logs-for-support/raw/main/debug-logs(no-headset-mic).tar.gz)

**Comment by ChocolateLoverRaj** [comment]
This may be happening to my Jinlon too. I am using NixOS configuration using chromebook-ucm-conf at `1328e46bfca6db2c609df9c68d37bb418e6fe279` (6 months ago) and the headphone mic works. However, I upgraded the chromebook-ucm-conf to the latest commit and the headphone mic stops working. This may be an issue with my NixOS configuration, so I'm going to test it on Fedora 40 KDE and see if it has the same issue.

You could also test it on ur delbin with https://github.com/ChocolateLoverRaj/chromebook-linux-audio/tree/redrix-temp and see if it works. (`redrix-temp`) is just a branch which does the audio script from 6 months ago, it should work on all devices that worked 6 months ago).

**Comment by ChocolateLoverRaj** [comment]
Here are the results of my testing
Branch | Jinlon | Redrix
-- | -- | --
`b6ce2a76f6360b87bfe593ff14dffc125fd9c671` | No | Yes
`1328e46bfca6db2c609df9c68d37bb418e6fe279` | Yes | *didn't test*

Conclusion: Somewhere between 1328e46bfca6db2c609df9c68d37bb418e6fe279 and b6ce2a76f6360b87bfe593ff14dffc125fd9c671 headphone mic stopped working for Jinlon (and maybe Delbin too)

**Comment by CoolPenguin27** [comment]
Fixed with this pr in the ucm repo: [sof-rt5682: add headset mic support](https://github.com/WeirdTreeThing/chromebook-ucm-conf/pull/6).
