### ISSUE TITLE
Headphone audio not working. (Blooglet)

### ISSUE THREAD

**Issue by Froggio5543** [WeirdTreeThing/chromebook-linux-audio#108]
After running the script the speakers work fine but it does not play sound through my headphones when they are plugged in. Instead it continues to play on the speakers. It does seem to register both the headphone mic and speakers but it does not play sound through them even when selected as the audio output. 

**Boardname**
Blooglet 

**Logs**
[Uploading debug-logs.tar.gz…]()

**Comment by Froggio5543** [comment]
never mind I changed the wrong setting lmao mb

**Comment by WeirdTreeThing** [comment]
lmao
