### ISSUE TITLE
Do you have the old version of audio script for chromebook ubuntu 23.10 non lts?

### ISSUE THREAD

**Issue by ZAB303** [WeirdTreeThing/chromebook-linux-audio#111]
**Describe the bug**

**Boardname**
If you don't know where to find this, run `cat /sys/class/dmi/id/product_name`

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.

**Comment by ZAB303** [comment]
![image (1)](https://github.com/WeirdTreeThing/chromebook-linux-audio/assets/155524110/d36dbebe-a771-4cb3-a3c6-50ef1cac918d)

**Comment by WeirdTreeThing** [comment]
John Github has it saved somewhere

**Comment by ZAB303** [comment]
> John Github

Do you have the link?

**Comment by WeirdTreeThing** [comment]
[here](https://www.youtube.com/watch?v=IiLAAQCHMZM)

**Comment by ZAB303** [comment]
> [here](https://www.youtube.com/watch?v=IiLAAQCHMZM)

please don't joke, I've been looking for john github but can't find him, please help me

**Comment by ethanaobrien** [comment]
Just use Debian. It's literally ubuntu but like not bad

(Ubuntu is based on Debian for those who don't know)

**Comment by ninelore** [comment]
https://github.com/WeirdTreeThing/chromebook-linux-audio?tab=readme-ov-file#ubuntu
