### ISSUE TITLE
Redrix left speaker mapped to all real speakers (no stereo sound)

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [WeirdTreeThing/chromebook-linux-audio#115]
**Describe the bug**
If I play audio from the "Front Right" speaker, no sound gets played. If I play audio from the "Front Left" speaker, sound gets played (I'm pretty sure the sound is coming out of all speakers, not just one or two on the left). 
![image](https://github.com/WeirdTreeThing/chromebook-linux-audio/assets/52586855/56935bfc-7ebc-4007-9d86-08ef11871592)
Fedora 39

I'm surprised that I didn't realize this until just now. I've listened to hours of songs and nothing sounded wrong to me.

Also Redrix has 4 speakers so it would be cool if I was able to play sounds from 1 specific speaker.

**Boardname**
Redrix

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14784397/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
./setup-audio --branch redrix

**Comment by ChocolateLoverRaj** [comment]
After running the command I get no audio detected. 
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14796234/debug-logs.tar.gz)

**Comment by ChocolateLoverRaj** [comment]
Btw, I ran an old version of the script and ucm (https://github.com/ChocolateLoverRaj/chromebook-linux-audio/tree/redrix-temp) and left and right sound works as expected. So something probably broke since then. Here are logs after I ran the `redrix-temp` script in case they're helpful: 
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14796272/debug-logs.tar.gz)
This is a working UCM config commit: https://github.com/ChocolateLoverRaj/chromebook-ucm-conf/tree/redrix-temp

**Comment by WeirdTreeThing** [comment]
strace alsaucm reload &> alsaucm.log

**Comment by WeirdTreeThing** [comment]
with the broken ucm

**Comment by ChocolateLoverRaj** [comment]
[alsaucm.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14798808/alsaucm.log)

**Comment by ChocolateLoverRaj** [comment]
[alsaucm.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14798824/alsaucm.log)

**Comment by WeirdTreeThing** [comment]
try now

**Comment by ChocolateLoverRaj** [comment]
I'm going to install a Linux distro just to test it. Which one should I install for the sole purpose of testing this audio script?

(Currently only have NixOS, will add new audio script to NixOS later, plus I should probably test ucm conf on a distro that you support yourself)

**Comment by ChocolateLoverRaj** [comment]
I'll just install Fedora 39

**Comment by ChocolateLoverRaj** [comment]
Now there is sound but there is still the same left/right problem.
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14809782/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Edit /usr/share/alsa/ucm2/conf.d/codecs/max98390/speaker.conf and change PlaybackChannels from 2 to 4 and see what happens

**Comment by ChocolateLoverRaj** [comment]
I'm editing `/usr/share/alsa/ucm2/codecs/max98390/speaker.conf`, I think that's what you meant

**Comment by ChocolateLoverRaj** [comment]
The result is no audio output

**Comment by WeirdTreeThing** [comment]
Ok so the driver only configures stereo speakers then

**Comment by ChocolateLoverRaj** [comment]
I think maybe sounds won't even sound right if played from just a front speaker or just a back speaker cuz both speakers need to work together to produce all frequencies. I'm just guessing though. Practically the only use for having 4x audio channels for me would be for playing KDE sound settings and clicking on each speaker individually.

Also I can test stuff on chrome os if you want. I think chrome os might be doing stereo and not 4x.

**Comment by WeirdTreeThing** [comment]
> Btw, I ran an old version of the script and ucm (https://github.com/ChocolateLoverRaj/chromebook-linux-audio/tree/redrix-temp) and left and right sound works as expected. So something probably broke since then. Here are logs after I ran the `redrix-temp` script in case they're helpful: [debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14796272/debug-logs.tar.gz) This is a working UCM config commit: https://github.com/ChocolateLoverRaj/chromebook-ucm-conf/tree/redrix-temp

The codec init and speaker config are the same between that commit and my current redrix branch, so  I'm not sure how that one works but this one doesn't.

**Comment by ChocolateLoverRaj** [comment]
Maybe it's a different file that causes the bug?

**Comment by WeirdTreeThing** [comment]
Unlikely, but feel free to mess around with ucm

**Comment by ChocolateLoverRaj** [comment]
1. I ran the audio script in this repo in the main branch.
2. I replaced `/usr/share/alsa/ucm2/conf.d/sof-rt5682` with https://github.com/WeirdTreeThing/chromebook-ucm-conf/tree/1328e46bfca6db2c609df9c68d37bb418e6fe279/adl/sof-rt5682
3. Audio worked with left and right

**Comment by ChocolateLoverRaj** [comment]
Another thing I did:
1. I removed `/usr/share/alsa`
2. I reinstalled `alsa-ucm`, `alsa-lib`, and `alsa-utils`
3. I ran the audio script, normal repo and branch
4. Audio worked with left and right

I am very bamboozled. I am going to re-install Fedora and see if I can reproduce this.

**Comment by ChocolateLoverRaj** [comment]
I tried https://github.com/ChocolateLoverRaj/chromebook-ucm-conf/tree/fix-redrix-stereo and now I get left and right sound. However, on the right side, sound is only coming out of the bottom speaker and not the top speaker.

**Comment by WeirdTreeThing** [comment]
@ChocolateLoverRaj we can close this, right?

**Comment by ChocolateLoverRaj** [comment]
Yes
