### ISSUE TITLE
Asus C302C has no audio

### ISSUE THREAD

**Issue by davealdr** [WeirdTreeThing/chromebook-linux-audio#117]
Describe the bug
there is no audio out of the built-in speakers headphone jack or HDMI

Boardname
cave

Logs
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14796008/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
This should be fixed now, git pull and try the script again.
