### ISSUE TITLE
No audio on KANO (Acer Chromebook Spin 714 2023  - CP714-2W-56B2)

### ISSUE THREAD

**Issue by tinker2much** [WeirdTreeThing/chromebook-linux-audio#120]
Ran the audio script as instructed, no audio from the internal speakers. 

NOTE: The previous model of the Chromebook Spin 714 (also KANO) is listed on the supported devices page, not this specific one. I'm using Mr Chromebox's firmware, no problem there. I have gone chromebook->linux before on an old Acer CB3-111, but it's been a long time. I'm comfortable at the command line, just let me know whatever I can furnish or do that might help you. 

Generating the debugging information didn't work (see below). No file was produced. The script said I needed to install pciutils, but that's already installed: 

```
@deb714:~/Documents/chromebook-linux-audio$ bash debugging.sh 
Welcome.
This script will ask you for sudo password, which is necessary to extract required information.
--2024-04-01 16:53:47--  https://mrchromebox.tech/files/util/cbmem.tar.gz
Resolving mrchromebox.tech (mrchromebox.tech)... 78.47.63.107
Connecting to mrchromebox.tech (mrchromebox.tech)|78.47.63.107|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21705 (21K) [application/x-gzip]
Saving to: ‘cbmem.tar.gz’

cbmem.tar.gz                       100%[================================================================>]  21.20K   104KB/s    in 0.2s    

2024-04-01 16:53:48 (104 KB/s) - ‘cbmem.tar.gz’ saved [21705/21705]

Failed to stop pipewire.socket: Unit pipewire.socket not loaded.
Failed to stop pipewire.service: Unit pipewire.service not loaded.
Failed to start pipewire.socket: Unit pipewire.socket not found.
Failed to start pipewire.service: Unit pipewire.service not found.
lspci not found. Please install pciutils.
Log collection done.
Please upload "debug-logs.tar.gz" for analysis.

@deb714:~/Documents/chromebook-linux-audio$ sudo apt install pciutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pciutils is already the newest version (1:3.9.0-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Press any key to continue...



```

**Comment by tinker2much** [comment]
oops, found the debug file, see attached...
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14829422/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Install pipewire-bin and run the debug script again

**Comment by tinker2much** [comment]
"Install pipewire-bin and run the debug script again"
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14843779/debug-logs.tar.gz)

**Comment by MoldyTaint** [comment]
Receiving the same issues with the Acer 714 laptop. Everything is working but the Audio.
