### ISSUE TITLE
IP6 / other module support in the Debian kernel?

### ISSUE THREAD

**Issue by jeffmcneill** [WeirdTreeThing/chromebook-linux-audio#121]
**Describe the bug**
Getting errors enabling IP6 in UFW and it keeps pointing to lack of module support (IP6 or other) in the kernel. If I turn ufw logging off I can get it to work, but not with logging on.

Note, the script does allow an external USB sound card to work but not the internal speakers or microphone.

**Boardname**
Ampton (ASUS C214MA)

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.

Cannot get a log file, it errors on not finding `lspci` however, the latest version of pciutils is already installed on the system.

**Comment by WeirdTreeThing** [comment]
Make an issue at  https://github.com/chrultrabook/debian-kernel.
