### ISSUE TITLE
Arch linux with pipewire no card listed

### ISSUE THREAD

**Issue by socphoenix** [WeirdTreeThing/chromebook-linux-audio#122]
**Describe the bug**
After running the script and rebooting, pactl list sinks only shows dummy output

**Boardname**
If you don't know where to find this, run `cat /sys/class/dmi/id/product_name`
Meep

**Logs**
Generate logs with `[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14928994/debug-logs.tar.gz)` and attach the output here.

The script worked about a year ago on the same laptop, unsure what has changed besides a fresh install.

**Comment by socphoenix** [comment]
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14929006/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Oh this is a stupid stock firmware bug

**Comment by WeirdTreeThing** [comment]
Workaround is `echo "options snd-intel-dspcfg dsp_driver=3" > /etc/modprobe.d/sof.conf` as root.

**Comment by socphoenix** [comment]
Thank you! This fixed the issue.
