### ISSUE TITLE
Kernel installation error on Debian 12.5

### ISSUE THREAD

**Issue by riblettmj** [WeirdTreeThing/chromebook-linux-audio#123]
**Describe the bug**
Running the script, first prompts for installation of the custom kernel.  After accepting [Y] the script indicates that this may take some time, howeer after about 3 seconds displays "Error: Failed to install kernel".  Upon inspection, I cannot seem to access the Github aritfact for the debian-kernel.zip through the nightly.link (script can't either).

**Boardname**
Nightfury

**Comment by WeirdTreeThing** [comment]
I haven't done the greatest job at maintaining that kernel, I just updated it so after github actions builds it, the link should work again.

**Comment by d3vnate** [comment]
Just trying to get this to work myself.  Doesn't seem to be working yet but I'm stoked that you're more or less on top of fixing it WeirdTreeThing.

**Comment by WeirdTreeThing** [comment]
It will take about an hour for CI to build the kernel.

**Comment by Ser1ous1** [comment]
Hello,

does not work again with debian 12.7 :( same error message

**Comment by WeirdTreeThing** [comment]
I just started another build
