### ISSUE TITLE
request for support on HP Chromebook 11 G5 EE

### ISSUE THREAD

**Issue by donavan-blsd** [WeirdTreeThing/chromebook-linux-audio#128]
Using mrchromebox's script I was able to get ChromeOS Flex to install on a non-supported (officially) Chromebook.  The reason is, updates, I can get them now using Flex over the vanilla ChromeOS.   Unfortunately the audio does not work.   I have not yet tried this fix on the device as there is no indication that it will be supported on ChromeOS specifically.  However I have noticed that most of the usage cases for this fix are for getting other OSes onto the Chrome devices.  I think you will start seeing a lot of people using your script (and mrchromebox's) in order to continue to get updates on older Chrome hardware.  In my case I was able to save around 500 machines from getting scrapped because I can now update past the last supported version of ChromeOS allowing them to be secure and thus supported.   I don't really know what the differences are with Flex over vanilla but it would seem to me the drivers and support should be there for ChromeOS or Flex if the device originally ran ChromeOS. 

DEVICE:
HP Chromebook 11" G5 EE (education edition)
Celeron N3060 4GB RAM, 16GB EMMC
Board name:  RELM

Printing on the board:
model NL6C
DANL6CMB6F0
RevF

**Comment by ellyq** [comment]
We don't support ChromeOS Flex.

**Comment by WeirdTreeThing** [comment]
Even if I wanted to support flex, I can't due to the OS being immutable. You can enable writing to rootfs, but updates will wipe away any changes you make.
