### ISSUE TITLE
Speakers not working on Ubuntu 22.10 ASUS C302 (Cave)

### ISSUE THREAD

**Issue by tek112** [WeirdTreeThing/chromebook-linux-audio#13]
Running Ubuntu 22.10 and installed audio script and headphone detection. Sound still shows dummy output.

**Comment by WeirdTreeThing** [comment]
As stated in the README, Ubuntu will not work and I don't have the time to maintain fixes for it.

**Comment by tek112** [comment]
> As stated in the README, Ubuntu will not work and I don't have the time to maintain fixes for it.

I appreciate you maintaining this, but it says Ubuntu may or may not work because of outdated packages. I tested and it doesn't work. I agree with closing the issue, but maybe update the readme?
