### ISSUE TITLE
It works fine on Ubuntu 24

### ISSUE THREAD

**Issue by geekaz01d** [WeirdTreeThing/chromebook-linux-audio#132]
I don't understand the motivation for your trolling but if you comment out lines 338 and 339, this script runs fine on Ubuntu 24 with a TANIKS (adl) board. It's also rumored to work fine on other recent builds.

If you are going to delete this issue I'm just going to fork your project.

Or I could regression test it and just fix it in PRs.

I've already put enough time into looking for the problem to realize there wasn't one, so I'm motivated by general irritation.

**Comment by nathblade16** [comment]
I'm sorry but ubuntu support depends on the driver that gets installed, sometimes it works fine and in my case it does not work on ubuntu, this is not trolling and just because it works for you does not mean it works for every one else

**Comment by geekaz01d** [comment]
I get that you don't want to do the work, or that you might even neglect that part of the project.

But there is no reason to obfuscate the fact that it might work. We know it's a moving target. Imperfection can exist. It's okay.

**Comment by nathblade16** [comment]
> I get that you don't want to do the work, or that you might even neglect that part of the project.
> 
> But there is no reason to obfuscate the fact that it might work. We know it's a moving target. Imperfection can exist. It's okay.

1. I am not the creator of this project
2. This script uses drivers from intel/amd so its not a matter of work, its a matter of intel needing to fix the drivers

**Comment by geekaz01d** [comment]
1. Sorry. I shouldn't reply from mobile without reading glasses.
2. I agree. That is a totally valid point.
