### ISSUE TITLE
[Caroline] No audio on Fedora 39, kernel 6.8.10

### ISSUE THREAD

**Issue by bitrot-alpha** [WeirdTreeThing/chromebook-linux-audio#134]
**Describe the bug**
No audio on Fedora 39 after updating to latest kernel 6.8.10 (sound menu shows "Dummy Output"). Audio worked fine on previous kernel.

**Boardname**
Caroline

**Logs**
`debugging.sh` didn't produce a tar file, Fedora 39 doesn't allow debugmem access :(

**Comment by bitrot-alpha** [comment]
audio works fine on kernel 6.8.9 :upside_down_face:

**Comment by bitrot-alpha** [comment]
upgraded to fedora 40, issue persists

**Comment by theflyingsquirrel88** [comment]
I just installed Fedora 40 cinnamon and there is no sound with the script. 
Is there a way to downgrade to kernel 6.8.9?

**Comment by po1o** [comment]
Exact same issue here - I tested that booting to 6.8.5 fixes the issue.

**Comment by bitrot-alpha** [comment]
It works now! Fedora 40 with kernel 6.9.7 sound works. Thanks!
