### ISSUE TITLE
No audio on Tigerlake Lenovo Flex 5i running PopOs

### ISSUE THREAD

**Issue by bewuwy** [WeirdTreeThing/chromebook-linux-audio#138]
**Describe the bug**
I ran the script, but there is no sound and PopOs still shows "Dummy output". I enabled the sound controller using pavu control and there are sound outputs detected, but there is still no sound.

**Boardname**
Lillippup

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.
[debug-logs.tar.gz](https://github.com/user-attachments/files/15729089/debug-logs.tar.gz)

**Comment by ellyq** [comment]
Audio on TigerLake works with kernel 6.6 and newer. Closing.
