### ISSUE TITLE
[Board Atlas] Speakers no longer recognized with Kernel 6.8.11 

### ISSUE THREAD

**Issue by po1o** [WeirdTreeThing/chromebook-linux-audio#139]
**Describe the bug**
Kernel 6.8.11 -- Audio works fine via headphones. However the laptop speakers are not detected.
It works fine with Kernel 6.8.5. I haven't tested kernels in between.

**Boardname**
Atlas

**Comment by delete-your-github-today** [comment]
Might be the same problem here. Atlas board, running Debian Sid. Kernel 6.8.12 fails, reverting to the next most recent in Debian (6.7.12+bpo-rt) fixes audio again.

I guessed that the issue might be a conflict between the snd_soc_avs and friends that this project installs, and the new SOF project modules. I tried adding some blacklist entries to modprobe.d for each of the SOF modules that were being loaded, but that didn't fix it:
```
blacklist snd_sof_pci_intel_skl
blacklist snd_sof_intel_hda_common
blacklist snd_sof_intel_hda_mlink
blacklist snd_sof_intel_hda
blacklist snd_sof_pci
blacklist snd_sof_xtensa_dsp
blacklist snd_sof
blacklist snd_sof_utils
```

**Comment by WeirdTreeThing** [comment]
It's not gonna be a module conflict. Most likely it is a regression in the AVS driver.

**Comment by po1o** [comment]
kernel 6.9.4 & 6.9.7 -- same issue
Hope this will get fixed soon upstream.

Since this is likely not actionable for [chromebook-linux-audio](https://github.com/WeirdTreeThing/chromebook-linux-audio) perspective, I am tempted to close this issue.

**Comment by WeirdTreeThing** [comment]
Try the script again

**Comment by po1o** [comment]
It works now! Speaker works fine on kernel 6.9.7
Thank you so much!
