### ISSUE TITLE
Asus 433t No speaker Sound - Manjaro KDE (multiple kernels) - Shyvanna

### ISSUE THREAD

**Issue by Paulie76** [WeirdTreeThing/chromebook-linux-audio#144]
Based on previous issues, I've tried running various kernels and reinstalling the script multiple times.  But still no joy.  

Audio settings ends up showing multiple "Built in Audio" options.  One of which is headphones, the other two are ??? Headphones have the three options of "off, default, Pro Audio".  The two others have only "off, Pro Audio".

dmesg logs show the following multiple errors:

[   22.981080] snd_soc_avs 0000:00:1f.3: module-type create failed: -2
[   22.981082] snd_soc_avs 0000:00:1f.3: error creating module -2
[   22.981141] snd_soc_avs 0000:00:1f.3: create path failed: -2
[   22.981143] snd_soc_avs 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on DMIC Pin: -2
[   22.981149]  DMIC: ASoC: error at __soc_pcm_hw_params on DMIC: -2
[   22.981152]  Digital Microphone: ASoC: error at dpcm_fe_dai_hw_params on Digital Microphone: -2
[   22.981333] snd_soc_avs 0000:00:1f.3: no DMIC ep_blob found
[   22.981335] snd_soc_avs 0000:00:1f.3: module-type create failed: -2
[   22.981338] snd_soc_avs 0000:00:1f.3: error creating module -2
[   22.981395] snd_soc_avs 0000:00:1f.3: create path failed: -2
[   22.981397] snd_soc_avs 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on DMIC Pin: -2
[   22.981401]  DMIC: ASoC: error at __soc_pcm_hw_params on DMIC: -2
[   22.981403]  Digital Microphone: ASoC: error at dpcm_fe_dai_hw_params on Digital Microphone: -2
[   22.981610] snd_soc_avs 0000:00:1f.3: no DMIC ep_blob found
[   22.981612] snd_soc_avs 0000:00:1f.3: module-type create failed: -2

....and so on and so on down the line. until it gets to the bluetooth, which it initializes correctly.

This is a Shyvanna board.  And I've attached the debug log as necessary.

Thanks!

**Comment by Paulie76** [comment]
[debug-logs.tar.gz](https://github.com/user-attachments/files/15876431/debug-logs.tar.gz)

**Comment by Paulie76** [comment]
Issue is resolved.  

Had to go into alsamixer, turn up the dsm on each of the sound options, and then move a playing video from audio source to audio source until it picked up.

I don't know why there are so many sources in my audio list.  (I'm assuming one for headset, one for speakers, and one for each of the USB-C ports which read as HDMI audio?)  But the applet in KDE just doesn't do a good job of identifying which is which; labelling them all Source 1, Source 2, Source 3, etc...  It wasn't until *after* I ran aplay -l that I was able to sort of get on track with what was happening.

**Comment by Paulie76** [comment]
Marking completed

**Comment by WeirdTreeThing** [comment]
Can you run the audio script again and see if it fixes your source name issue? It should also fix the dsm issue, if you didn't manually fix it.

**Comment by Paulie76** [comment]
No luck on the sources naming.  Still just says "Built in Audio Pro 1, 2, 3, 4, etc..."

DSM had been fixed previously, so not sure if the script update did anything or not.

Thank you for trying, however.  I appreciate it.  As long as the sound works, the names don't really matter too much to me!
