### ISSUE TITLE
Missing snd_soc_avs_max98927 module in Debian

### ISSUE THREAD

**Issue by rhansen** [WeirdTreeThing/chromebook-linux-audio#146]
FYI, Debian's kernel config doesn't build the `snd_soc_avs_max98927` module, so built-in speakers won't work on machines that use MAX98927 such as `leona` (ASUS Chromebook C425).  For details, see [Debian bug #1076062](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076062).

I'll leave it up to you to determine whether it's worthwhile to implement a workaround in your script.  Steps to build the module are in the Debian bug report.

**Comment by WeirdTreeThing** [comment]
The script should have prompted you to install the custom kernel, which includes this module.
