### ISSUE TITLE
Error updating Linux kernel 

### ISSUE THREAD

**Issue by marcossglr** [WeirdTreeThing/chromebook-linux-audio#147]
I fixed the audio of my chromebook right yesterday and everything went great, I had to reinstall the OS today and it seems there's an error in the installation of the custom Linux kernel.

Can you help me to clarify this thing?.

I'm using debian 12 btw

**Comment by mrme8895** [comment]
You can compile the kernel manually, but I am not sure if it will work. Guides:[](https://www.debian.org/doc//manuals/debian-handbook/sect.kernel-compilation.html)

**Comment by marcossglr** [comment]
I installed the chrultrabook custom kermel manually with a .deb package and it worked perfectly.

**Comment by marcossglr** [comment]
Thank you for all of your work

**Comment by RollingStar** [comment]
Where did you get the .deb?

**Comment by marcossglr** [comment]
Yep, it's that.

There's a couple of other issues like this, and I found a mirror browsing around, I'll see if I can edit this comment with the link.

I tried this with PopOs, which is a distro I love, but the Linux Kernel in PopOs is v6.8... and PopOs has not an easy way to set a kernel version to boot.
