### ISSUE TITLE
Kernel .deb is now 404

### ISSUE THREAD

**Issue by RollingStar** [WeirdTreeThing/chromebook-linux-audio#148]
**Describe the bug**

The link in the code is no longer valid.

https://nightly.link/chrultrabook/debian-kernel/workflows/build/main/debian-kernel.zip

I found this which looks like it's from WeirdTreeThing, but no guarantees it works or is them. https://files.tree123.org/chrultrabook/debian-kernel/

I installed it with sudo apt install ./my.deb

no -y

it appears to have worked.

**Boardname**
asdf

**Logs**
asdf

**Comment by clm1919** [comment]
Can confirm that using the linked kernel worked for me a few days ago.

-downloaded .deb file

-installed kernel ($ sudo dpkg -i *.deb)

-rebooted

-ran WeirdTreeThing's amazing script (no kernel update message)

-picked "SOF" option

-rebooted

sound works

HP Chromebook 14 G5 Intel Celeron N3350/4GB/16GB (ApolloLake/SNAPPY)

**Comment by jy-user-coder** [comment]
I'm using a Chromebook whose codename is sentry with Debian 12. I compiled the linux kernel using the script from https://github.com/chrultrabook/debian-kernel. The script runs well on my laptop, after dependencies properly installed. With the customized kernel installed, the scripts of this repo runs well and the audio works now.

**Comment by WeirdTreeThing** [comment]
There is a new build of the kernel up now.
