### ISSUE TITLE
Lenovo IP Flex 5 Chrome 14IAU7 - Debian. No sound device. Driver in use: snd_hda_intel

### ISSUE THREAD

**Issue by gdbaldw** [WeirdTreeThing/chromebook-linux-audio#149]
**Describe the bug**
No sound device. No Hardware Output Devices Available in Audio Mixer 

**Boardname**
Taeko

**Logs**
[debug-logs.tar.gz](https://github.com/user-attachments/files/16283570/debug-logs.tar.gz)

**Comment by gdbaldw** [comment]
00:1f.3 Multimedia audio controller [0401]: Intel Corporation Raptor Lake-P/U/H cAVS [8086:51ca] (rev 01)
	DeviceName: Multimedia audio controller
       ...
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

I've read of solutions that blacklist snd_hda_intel, or that start pulseaudio with snd_sof_pci_intel_tgl. Haven't seen a preferred implementation for Debian.

**Comment by clm1919** [comment]
just checking

assuming your ran WeirdTreeThing's audio script
did you notice if the kernel was updated successfully?
are you using a kernel 6.4 or above?

you might want to look here: https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/148

-------------------------------------------------------------------------
just a newbie offering advice that worked for me

**Comment by gdbaldw** [comment]
Yes, ran `audio script` without errors

uname -a
Linux debian 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

**Comment by clm1919** [comment]
Most of the advice I've read suggest a kernel 6.4 or higher.

(and i confess I'm a Noob-all-over-again trying Linux after many years)

$ uname -a
Linux debianhp14g5 6.6.0-chrultrabook #2 SMP PREEMPT_DYNAMIC Sat Nov  4 08:20:02 EDT 2023 x86_64 GNU/Linux

HP Chromebook 14 G5 Intel Celeron N3350/4GB/16GB (ApolloLake/SNAPPY)

Debian 12

**Comment by gdbaldw** [comment]
I blacklisted snd_hda_intel. But, now no kernel module is in use.

To blacklist in Debian:

    Create a file '/etc/modprobe.d/snd_hda_intel-blacklist.conf' containing 'blacklist snd_hda_intel'.
    Run 'depmod -ae' as root
    Recreate your initrd with 'update-initramfs -u'

`lspci -knn`

00:1f.3 Multimedia audio controller [0401]: Intel Corporation Raptor Lake-P/U/H cAVS [8086:51ca] (rev 01)
	DeviceName: Multimedia audio controller
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

**Comment by gdbaldw** [comment]
> > Haven't seen a preferred implementation for Debian.
> 
> Using kernel 6.6 or newer is the preferred solution, since that's when my patch landed that selects the correct driver automatically.

Thank you! I reversed the blacklist, then full-upgrade from Bookworm to Trixie. Sound Works now.
