### ISSUE TITLE
Fedora Silverblue?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [WeirdTreeThing/chromebook-linux-audio#15]
I'm interested in trying out Fedora Silverblue, but the directory for the sound drivers is read-only. Is there another way or workaround to get audio to work on Fedora Silverblue?

I don't know much about Fedora Silverblue, but here is what I'm thinking:
- Make a package for `rpm-ostree`?
- Fork Fedora Silverblue to include the drivers by default?

**Comment by WeirdTreeThing** [comment]
You would have to create custom packages for the UCM. I am not interested in supporting silverblue so you are on your own.
