### ISSUE TITLE
Request for .deb kernel headers 6.6.25-chrultrabook

### ISSUE THREAD

**Issue by kolotxoz** [WeirdTreeThing/chromebook-linux-audio#153]
This is not a bug report, but rather a request, is it possible to ask for the .deb package of the kernel headers for the version "6.6.25-chrultrabook", i'm using debian, and they are needed for the use of virtualbox.

Thanks in advance

**Comment by WeirdTreeThing** [comment]
Duplicate of https://github.com/chrultrabook/debian-kernel/issues/4

**Comment by kolotxoz** [comment]
Did'nt knew that it was a duplicate request, thx for the quick response
