### ISSUE TITLE
Arch Linux with Pipewire No Sinks Listed

### ISSUE THREAD

**Issue by philipsiu** [WeirdTreeThing/chromebook-linux-audio#155]
**Describe the bug**
Arch Linux
6.6.42-1-lts

Only sink available is the 'Dummy Output' when there are no headphones plugged in. Confirmed that sof-firmware package is installed and ran the audio script with a reboot. Still the same issue. Added module settings workaround in the issue below. Didn't fix the issue.
- _Originally posted by @WeirdTreeThing in https://github.com/WeirdTreeThing/chromebook-linux-audio/issues/122#issuecomment-2052896157_

'Alder Lake PCH-P High Definition Audio Controller [alsa]' is listed when running pactl and wpctl. However when I plug a pair of headphones in they list the four 'DisplayPort' sinks and the 'Headphones' sink.

**Boardname**
Osiris

**Logs**
[debug-logs.tar.gz](https://github.com/user-attachments/files/16401361/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Run the audio script again and see if it works.

**Comment by philipsiu** [comment]
> Run the audio script again and see if it works.

It worked. Thanks.
