### ISSUE TITLE
404 Error during installation

### ISSUE THREAD

**Issue by j3n0v4** [WeirdTreeThing/chromebook-linux-audio#159]
Hello,

The script is running into a 404 error. The script is trying to download **https://github.com/thesofproject/avs-topology-xml/releases/download/v2024.02/avs-topology_2024.02.tar.gz** which does not exist anymore. Therefore the script fails.

**Comment by glotim** [comment]
Same problem here. They either deleted the files or moved them.

**Comment by Apok01** [comment]
Installing topology
Traceback (most recent call last):
  File "/home/apo/chromebook-linux-audio/./setup-audio", line 319, in <module>
    match_platform(board)
  File "/home/apo/chromebook-linux-audio/./setup-audio", line 95, in match_platform
    avs_audio()
  File "/home/apo/chromebook-linux-audio/./setup-audio", line 151, in avs_audio
    urlretrieve(url=avs_tplg_url, filename="/tmp/avs_tplg/avs-tplg.tar.gz")
  File "/usr/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by therealkuking** [comment]
I have the same issue as above, on Fedora 40.

**Comment by mhungerford** [comment]
Hopefully the original "built" avs-topology_2024.02.tar.gz gets re-uploaded, but I got mine working the hard way... 

you need to build avstplg to build avs-topology, and avstplg is from avsdk

download avsdk:
git clone https://github.com/thesofproject/avsdk.git
cd avstplg
make
#if you have problems building it, you likely need to install dotnet sdk
#sudo apt install dotnet-sdk-6.0 dotnet-host dotnet-hostfxt-6.0

# build avs-topology (tag: v2024.02) using avstplg:
git clone --branch v2024.02 https://github.com/thesofproject/avs-topology-xml.git 
# run make pointing to where avstplg binary is
PATH=$PATH:$HOME/avsdk/avstplg/build/bin/Debug/net6.0/publish make
# to create the lib and final release tar.gz 
make dist

# install avs-topology.tar.gz to dir for setup-audio script:
sudo mkdir -p /tmp/avs_tplg
sudo tar -xvf avs-topology.tar.gz -C /tmp/avs_tplg/

#modify setup-audio to avoid downloading/installing missing file:
vi setup-audio
# comment out lines 152 and 153 (urlretrieve and tar xv)
# run setup-audio
sudo ./setup-audio

**Comment by koluckirafal** [comment]
As a workaround* (not involving building the topology files from source) you can try manually installing topology files from `linux-firmware` repository, as the binaries were recently moved there: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs

* you would still need to comment out this part of the script: https://github.com/WeirdTreeThing/chromebook-linux-audio/blob/main/setup-audio#L151-L154

**Comment by j3n0v4** [comment]
> Hopefully the original "built" avs-topology_2024.02.tar.gz gets re-uploaded, but I got mine working the hard way...
> 
> you need to build avstplg to build avs-topology, and avstplg is from avsdk
> 
> download avsdk: `git clone https://github.com/thesofproject/avsdk.git` `cd avstplg` `make` if you have problems building it, you likely need to install dotnet sdk `sudo apt install dotnet-sdk-6.0 dotnet-host dotnet-hostfxt-6.0`
> 
> build avs-topology (tag: v2024.02) using avstplg: `git clone --branch v2024.02 https://github.com/thesofproject/avs-topology-xml.git` run make pointing to where avstplg binary is `PATH=$PATH:$HOME/avsdk/avstplg/build/bin/Debug/net6.0/publish make` to create the lib and final release tar.gz `make dist`
> 
> install avs-topology.tar.gz to dir for setup-audio script: `sudo mkdir -p /tmp/avs_tplg` `sudo tar -xvf avs-topology.tar.gz -C /tmp/avs_tplg/`
> 
> modify setup-audio to avoid downloading/installing missing file: `vi setup-audio` comment out lines 152 and 153 (urlretrieve and tar xv) run setup-audio `sudo ./setup-audio`

Many thanks for this explanation. I got my audio working.

**Comment by Custard-Tart** [comment]
> Hopefully the original "built" avs-topology_2024.02.tar.gz gets re-uploaded, but I got mine working the hard way...
> 
> you need to build avstplg to build avs-topology, and avstplg is from avsdk
> 
> download avsdk: `git clone https://github.com/thesofproject/avsdk.git` `cd avstplg` `make` if you have problems building it, you likely need to install dotnet sdk `sudo apt install dotnet-sdk-6.0 dotnet-host dotnet-hostfxt-6.0`
> 
> build avs-topology (tag: v2024.02) using avstplg: `git clone --branch v2024.02 https://github.com/thesofproject/avs-topology-xml.git` run make pointing to where avstplg binary is `PATH=$PATH:$HOME/avsdk/avstplg/build/bin/Debug/net6.0/publish make` to create the lib and final release tar.gz `make dist`
> 
> install avs-topology.tar.gz to dir for setup-audio script: `sudo mkdir -p /tmp/avs_tplg` `sudo tar -xvf avs-topology.tar.gz -C /tmp/avs_tplg/`
> 
> modify setup-audio to avoid downloading/installing missing file: `vi setup-audio` comment out lines 152 and 153 (urlretrieve and tar xv) run setup-audio `sudo ./setup-audio`

I'm having trouble getting this working. When I get to 

> run make pointing to where avstplg binary is `PATH=$PATH:$HOME/avsdk/avstplg/build/bin/Debug/net6.0/publish 

I encounter the following 

`You must install or update .NET to run this application.

App: /home/user/avsdk/avstplg/build/bin/Debug/net6.0/publish/avstplg
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet

The following frameworks were found:
  8.0.8 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.24.04-x64&os=linuxmint.22
`
But the package for dotnet-runtime-6.0 is no longer available.

**Comment by therealkuking** [comment]
The AVS firmware is now shipping with Fedora 40. Update your system to get the latest kernel  (sudo dnf update). Then comment out lines 151 through 154 in the audio script, and then run the script. It should install without issues.

**Comment by lukeallister** [comment]
Same for me on OpenSUSE tumbleweed (after system update): I only had to comment lines 151-154 and the AVS firmware was already available.

**Comment by jimibananas** [comment]
> The AVS firmware is now shipping with Fedora 40. Update your system to get the latest kernel (sudo dnf update). Then comment out lines 151 through 154 in the audio script, and then run the script. It should install without issues.

Thank you > therealkuking   -Worked perfectly on Fedora 40.

**Comment by thethirdmurph** [comment]
> The AVS firmware is now shipping with Fedora 40. Update your system to get the latest kernel (sudo dnf update). Then comment out lines 151 through 154 in the audio script, and then run the script. It should install without issues.

Doesn't seem to work with Fedora on kernel 6.10.7

**Comment by livexia** [comment]
> Doesn't seem to work with Fedora on kernel 6.10.7

My device is Pixelbook Go.I found out with Fedora on kernel 6.10.7 the tplg file is somehow missing, maybe the kernel update deleting them.

But you can just downlod the tplg files from this repo `conf/avs/tplg` and put them in the `/lib/firmware/intel/avs` (see: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs).

**Comment by thethirdmurph** [comment]
> > > Doesn't seem to work with Fedora on kernel 6.10.7
> > 
> > 
> > My device is Pixelbook Go.I found out with Fedora on kernel 6.10.7 the tplg file is somehow missing, maybe the kernel update deleting them. You can find the missing tplg error in demsg.
> > Just downlod the tplg files from this repo `conf/avs/tplg` and put them in the `/lib/firmware/intel/avs` (see: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs).
> 
> My Case Chromebook Pro, Files from this URL did not help. But the files from `6.10.6` under `/lib/firmware/intel/avs` work fine for me.

I also had this experience.  in fedora 6.10.6 files ended tplg.bin.xz: however these files worked fine for me in debian where the files end in tplg.bin

**Comment by livexia** [comment]
I am just using files inside [this folder](https://github.com/WeirdTreeThing/chromebook-linux-audio/tree/main/conf/avs/tplg).
