### ISSUE TITLE
No audio PopOS HP Chromebook x360 14c (Eldrid)

### ISSUE THREAD

**Issue by wadewhitman** [WeirdTreeThing/chromebook-linux-audio#167]
The script runs and the system reboots, but still only shows dummy as the audio device.

Boardname is Eldrid

Logs
[debug-logs-Eldrid-2024-09-02_19h05m.tar.gz](https://github.com/user-attachments/files/16842668/debug-logs-Eldrid-2024-09-02_19h05m.tar.gz)

**Comment by wadewhitman** [comment]
It must be something with PopOS because every OS seems to work....  

I have verified the following work:

Arch
Fedora
LMDE 6
Ubuntu

**Comment by ellyq** [comment]
`[  113.133220] sof-audio-pci-intel-tgl 0000:00:1f.3: sof_ipc3_keyword_dapm_event: Failed to trigger widget DETECT12.0`
There's clearly a regression in kernel used by popOS. You can install kernel from Ubuntu if you want to use this particular distribution.

I'm daily-driving ELDRID on Fedora, it works flawlessly.

**Comment by wadewhitman** [comment]
I reloaded Fedora again and speakers work fine, just wish we could get the microphone working….

I’ve found that Arch usually shows less errors on dmesg boots and hopefully future kernel updates can fix the sound issues completely

I’ve tried compiling kernels etc….

I even got the kernel config from developer mode and tried compiling kernel 5.4.280 that is installed on the Chromebook itself…

It seems to compile the kernel, but the module for the sound card craps out because it’s missing a file tgl_guc_49.0.1.bin

I even got that file from the chrome install to no avail…..

I’ll just keep hacking on this thing….



Sent from my iPhone

On Sep 13, 2024, at 6:41 AM, Alicja Michalska ***@***.***> wrote:

﻿

[ 113.133220] sof-audio-pci-intel-tgl 0000:00:1f.3: sof_ipc3_keyword_dapm_event: Failed to trigger widget DETECT12.0
There's clearly a regression in kernel used by popOS. You can install kernel from Ubuntu if you want to use this particular distribution.

I'm daily-driving ELDRID on Fedora, it works flawlessly.
