### ISSUE TITLE
wget issue

### ISSUE THREAD

**Issue by g1001** [WeirdTreeThing/chromebook-linux-audio#169]
**Describe the bug**

I think the problem relates to the script looking for alsa-utils (see below) and not finding the installed one.

Here's the wget run with its output:

$ wget https://raw.githubusercontent.com/chrultrabook/
linux-tools/main/debugging.sh;bash debugging.sh
debugging.sh         100% [======================================================>]    1.27K    --.-KB/s
                         [Files: 1  Bytes: 1.27K [1.79KB/s] Redirects: 0  Todo: 0]
Welcome.
This script will ask you for sudo password, which is necessary to extract required information.
which: no alsaucm in (/home/adele/.local/bin:/home/adele/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin
:/usr/sbin:/sbin)
alsaucm not found. Please install alsa-utils.
Log collection done.
Please upload debug-logs-Nautilus-2024-09-05_08h32m.tar.gz for analysis.

^^^^ end of output

The log file produced is only 212 bytes, and its contents are:
no-alsautils  0 B
no-root         0 B
no-strace     0 B

The laptop is running Fedora Kinoite, so I tried to install alsa-utils with rpm-ostree as follows:

rpm-ostree install alsa-utils
error: "alsa-utils" is already provided by: alsa-utils-1.2.12-1.fc40.x86_64. Use --allow-inactive to expl
icitly require it.

So I guess the script will only accept the exact name "alsa-utils", without all the versioning added to the package name.

I'm not terribly familiar yet with the way Kinoite works, but I thought - maybe rrm-ostree is not the way I should be doing this - I should use toolbox instead. So I installed alsa-utils into the default toolbox using dnf.

I then ran setup-audio in the toolbox (producing same errors as in my other posted issue), and then did the wget.
Not only did it still NOT find alsa-utils, but now other commands, like lspci and lsusb, are NOT available in the toolbox.

**Boardname**
Nautilus

**Logs**
Since this is a wget issue, logs not relevant.

**Comment by livexia** [comment]
see: #159

**Comment by livexia** [comment]
> which: no alsaucm in (/home/adele/.local/bin:/home/adele/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin)

Maybe check the location of `alsaucm`, and then adding location path to the `$PATH` ?

**Comment by g1001** [comment]
Sorry for the late reply. Before trying livexia's suggestion, I avoided the whole issue by switching from Fedora Kinoite to Fedora Plasma Spin.

So closing this issue, even tho I can't confirm that livexia solved it.
