### ISSUE TITLE
No SOF install option for Asus C433 (SHYVANA)

### ISSUE THREAD

**Issue by LukeWarmpocket** [WeirdTreeThing/chromebook-linux-audio#176]
Typically, when I've run the script on other chromebooks, I'm presented with the option to choose between SOF or AVS. And if I choose AVS on a max98357a device, I'm presented with a warning about damaging the speakers. Neither of these things happened when I ran the script on my C433. The AVS script was installed automatically, and no warning was presented. I don't want to damage my speakers and I'm content to use a USB-C adapter for wired audio, so is there any way for me to run the script and get SOF on this device? Thanks.

**Comment by WeirdTreeThing** [comment]
SOF is not supported on that model. The option to choose between SOF and AVS is only available on Apollolake devices where both drivers are supported.

**Comment by grimmute** [comment]
For what it is worth, the script works perfectly on a ASUS C434TA (also Shyvana), both built-in speakers and the headphone jack are perfect.

I didn't configure anything during installation though, I just let the script do its thing and rebooted.

**Comment by WeirdTreeThing** [comment]
Another good point, shyvana doesn't even have max98357a. It has max98927 which supports peakvol to limit the speakers and should be fully safe to use.

**Comment by LukeWarmpocket** [comment]
Really? On https://docs.chrultrabook.com there's a Linux note for Shyvana
that states: "max98357a doesn't have a volume limiter so speakers could get
fried."

**Comment by LukeWarmpocket** [comment]
Thank you for your help, and for the script
