### ISSUE TITLE
It seems link for debian|PopOS custom kernel is not downloadable anymore ...

### ISSUE THREAD

**Issue by steve911it** [WeirdTreeThing/chromebook-linux-audio#18]
Could you please check ?

**Comment by WeirdTreeThing** [comment]
Yes, I know the person that hosts it and it is temporarily down. I have a mirror [here](https://tree123.org/files/debian-kernel/).

**Comment by tsoybe** [comment]
> Yes, I know the person that hosts it and it is temporarily down. I have a mirror [here](https://tree123.org/files/debian-kernel/).

Link shows: 404 Not Found

**Comment by WeirdTreeThing** [comment]
Sorry about that, new link [here](https://tree123.org/chrultrabook/debian-kernel/linux-image-6.1.27chrultrabook-fixups_6.1.27chrultrabook-fixups-8_amd64.deb).

**Comment by tsoybe** [comment]
Thx

**Comment by WeirdTreeThing** [comment]
Update: new kernel build so new link: [https://tree123.org/chrultrabook/debian-kernel/linux-image-6.5.4-chrultrabook_6.5.4-1_amd64.deb](https://tree123.org/chrultrabook/debian-kernel/linux-image-6.5.4-chrultrabook_6.5.4-1_amd64.deb)
(Old kernel name is still there as a symlink to the new kernel)

**Comment by toywood** [comment]
I have dpkg -i the 6.6 kernel in debian 12,and find the /dev/loop disapear.When i insmod loop,then cat /sys/block/loop*,there has no device with loop.I have try udevadm settle, and nothing changed.As i use debian-live ,the loop device is filesystem of squashfs.if have no loop,the debian live can not run on the kernel 6.6 deb package.Can you fix it? Thank you!
