### ISSUE TITLE
Audio not working on PopOS and Acer Chromebook Plus 515 (CB515-2H-52YD)

### ISSUE THREAD

**Issue by truefedex** [WeirdTreeThing/chromebook-linux-audio#181]
**Describe the bug**
Script seem to run succesfully. Outputs:
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing SOF
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1338, done.
remote: Counting objects: 100% (362/362), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 1338 (delta 186), reused 336 (delta 172), pack-reused 976 (from 1)
Receiving objects: 100% (1338/1338), 231.53 KiB | 363.00 KiB/s, done.
Resolving deltas: 100% (673/673), done.
Increasing alsa headroom (fixes instability)
Audio installed successfully! Reboot to finish setup.

If after reboot I run the script second time - it prints the same. But there are nor sound nor any "Sound output device" in system settings (except "Dummy Output" that silent)

**Boardname**
Omnigul

[debug-logs-Omnigul-2024-11-08_13h58m.tar.gz](https://github.com/user-attachments/files/17678126/debug-logs-Omnigul-2024-11-08_13h58m.tar.gz)

**Comment by WeirdTreeThing** [comment]
can you run `find /lib/firmware/intel &> firmware.txt` and upload firmware.txt

**Comment by truefedex** [comment]
[firmware.txt](https://github.com/user-attachments/files/17684431/firmware.txt)

**Comment by WeirdTreeThing** [comment]
Looks like this device is so new that popos doesn't have the required firmware for it packaged yet. You can try another distro such as fedora or arch since they have newer packages. If that works I'll see what I can do.

**Comment by truefedex** [comment]
@WeirdTreeThing I tested it with Fedora Linux 41 (Workstation Edition)
The same script output but now I can hear the distorted sound.
Settings app showing some "Speaker - Raptor Lake-P/U/H cAVS" device.
But unfortunately the sound is heavily distorted. It is impossible to use it in this form.

**Comment by WeirdTreeThing** [comment]
So that issue is now the same as #175

**Comment by truefedex** [comment]
Ok then, I will probably close this one
