### ISSUE TITLE
No audio, Asus CX1700CKA (Gallop) + Fedora 41

### ISSUE THREAD

**Issue by ColinKinloch** [WeirdTreeThing/chromebook-linux-audio#186]
**Describe the bug**
Dummy audio device listed. There's also 5 "pro-audio" outputs and 3 inputs, that don't work.

**Boardname**
Gallop

**Logs**
[debug-logs-Gallop-2024-11-25_23h12m_chromebook.tar.gz](https://github.com/user-attachments/files/17923506/debug-logs-Gallop-2024-11-25_23h12m_chromebook.tar.gz)

**Comment by WeirdTreeThing** [comment]
Same issue as #185
