### ISSUE TITLE
Unknown/Unsupported chromebook model: yahiko

### ISSUE THREAD

**Issue by altabrida** [WeirdTreeThing/chromebook-linux-audio#189]
**Describe the bug**
Unknown/Unsupported chromebook model: yahiko

**Boardname**
If you don't know where to find this, run `cat /sys/class/dmi/id/product_name`

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.
[debug-logs-Yahiko-2024-11-28_21h43m.tar.gz](https://github.com/user-attachments/files/17953790/debug-logs-Yahiko-2024-11-28_21h43m.tar.gz)

**Comment by WeirdTreeThing** [comment]
Added
