### ISSUE TITLE
Will this work on Debian 11 for SETZER??

### ISSUE THREAD

**Issue by MrMintbook** [WeirdTreeThing/chromebook-linux-audio#19]
I'm just wondering if this will work on SETZER with debian 11 because i am looking into installing debian 11 on it

I am not related to MrChromebox by the way

**Comment by WeirdTreeThing** [comment]
SETZER will work but you need to use Debian 12 instead of Debian 11.

**Comment by WeirdTreeThing** [comment]
Closing as there is not a real issue. If you do run into any problems, feel free to open another issue.
