### ISSUE TITLE
Unknown/Unsupported chromebook model: craaskino

### ISSUE THREAD

**Issue by th3keyboard** [WeirdTreeThing/chromebook-linux-audio#196]
**Describe the bug**
Unknown/Unsupported chromebook model: craaskino

**Boardname**
Craaskino

**Logs**
[debug-logs-Craaskino-2024-12-10_16h32m.tar.gz](https://github.com/user-attachments/files/18086734/debug-logs-Craaskino-2024-12-10_16h32m.tar.gz)

**Comment by WeirdTreeThing** [comment]
Added
