### ISSUE TITLE
Unknown/Unsupported chromebook model: Panther

### ISSUE THREAD

**Issue by matilli** [WeirdTreeThing/chromebook-linux-audio#201]
[](**Describe the bug**
I'm running the script on an Asus Chromebox CN60 with Fedora 41, which is supported by chrultrabook

**Boardname**
Panther

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.
)
[debug-logs-Panther-2024-12-18_18h34m.zip](https://github.com/user-attachments/files/18186969/debug-logs-Panther-2024-12-18_18h34m.zip)

**Comment by WeirdTreeThing** [comment]
Panther doesn't need this script.
