### ISSUE TITLE
On a Lenovo 100e 1st gen Chromebook; & Display Drivers either got messed up or whatever was controlling the Display Drivers got messed up.

### ISSUE THREAD

**Issue by CABLE353** [WeirdTreeThing/chromebook-linux-audio#207]
I have Debian 12 running off of my usb drive, & dual booted with chromeos. I installed it knowing audio would be somewhat of a problem, but I found this project & decided to give it a try. It installed everything ok from what I can tell(no error messages or anything), but now when I close my chromebook; debian turns my display off & goes into sleep mode like normal, but it can't get back out of sleep mode when I open it and I have to force shut off my chromebook. The display brightness slider bar no longer works either. It's a pretty unique issue & I don't know much about how this works, but I think it has to do with the kernel not having the driver paths or drivers themselves. It could also be that I used the setup script after installing packages like firmware-misc-nonfree & crap like that. When I tried to reinstall frimware-misc-nonfree after finding this unwanted behavior, I got this from the terminal:
![Screenshot from 2024-12-24 12-00-37](https://github.com/user-attachments/assets/58b5b19e-99b4-4249-8bfb-83badc8389b0)

I'm not sure what it means other than there is something maybe a driver missing from somewhere. Nothing else is wrong with my display. Right now I can't close my chromebook because it won't turn my display back on, & I can't control my screen brightness. Please help!

**Comment by WeirdTreeThing** [comment]
This isn't audio related

**Comment by CABLE353** [comment]
Yes it is. The kernel used to make the audio work from the speakers has messed up or has incomplete display drivers that need to be _fixed_. I'm submitting this as a _**bug**_ & therefore has the relevance to be looked at even though it isn't directly audio related.
