### ISSUE TITLE
No audio on Markarth (Acer Chromebook Plus 514 + AMD 7320C) on Fedora 41

### ISSUE THREAD

**Issue by sidsahay** [WeirdTreeThing/chromebook-linux-audio#210]
**Describe the bug**
Installed Fedora 41 with RW_LEGACY firmware, tried kernels 6.12.4 and 6.11.x. Ran script and it finishes fine, but nothing works. Only "dummy output". 

**Boardname**
Markarth (Acer Chromebook Plus 514, AMD Ryzen 7320C)

**Logs**
[debug-logs-Markarth-2024-12-29_20h28m.tar.gz](https://github.com/user-attachments/files/18271455/debug-logs-Markarth-2024-12-29_20h28m.tar.gz)

**Comment by WeirdTreeThing** [comment]
Looks like fedora may be missing the machine driver for this device in the kernel. Arch worked for me on this chromebook, so try that.

**Comment by sidsahay** [comment]
Thanks for the quick reply! Unfortunately, that didn't work. I installed Arch (+Cinnamon) and I'm still getting "Dummy Output". Here are the logs:
[debug-logs-Markarth-2024-12-29_23h37m.tar.gz](https://github.com/user-attachments/files/18272052/debug-logs-Markarth-2024-12-29_23h37m.tar.gz)

Alternatively, what Arch configuration (kernel, audio system, dm, etc) are you running? I can try to match it.

**Comment by WeirdTreeThing** [comment]
This is progress, the internal sound card is now being recognized. Looks like this is the same syntax version issue as #185.
Try this workaround: `./setup-audio --branch=syntax-7`

**Comment by sidsahay** [comment]
That worked! Speaker and mic now show up and work properly. Thanks!

**Comment by WeirdTreeThing** [comment]
You would need to talk to a fedora kernel dev to get the module enabled.
