### ISSUE TITLE
Mic not working in pixelbook 2017 with archlinux

### ISSUE THREAD

**Issue by xcpky** [WeirdTreeThing/chromebook-linux-audio#22]
as the title suggests, after running the script, the audio works but the mic is not detected. 
btw, I see in [Linux compatibility sheet](https://docs.google.com/spreadsheets/d/1udREts28cIrCL5tnPj3WpnOPOhWk76g3--tfWbtxi6Q/edit#gid=0), there is a known issue called _audio WIP_. What does that mean?

**Comment by WeirdTreeThing** [comment]
The pixelbook mic is currently not supported. WIP means work in progress.

**Comment by xcpky** [comment]
this [project](https://github.com/jmontleon/pixelbook-fedora) and [gentoo wiki](https://wiki.gentoo.org/wiki/Google_Pixelbook_(2017)#Audio) claim that by copying the firmware from chromeOS recovery image, both mic and speaker can work. I am not sure if your script is doing the same thing since you didn't explain your script in README, but this info might help?

**Comment by WeirdTreeThing** [comment]
Both of those use the legacy SKL drivers which have many problems, the newer AVS drivers have less problems and are being developed more but are still lacking some support like rt5514.

**Comment by WeirdTreeThing** [comment]
I don't explain what the script does in the README since there is a lot to cover and it does different things depending on which device you run it on. I do make the script print out each step that it does while it runs and you can always just go read it.

**Comment by WeirdTreeThing** [comment]
We can test pixelbook mic now

**Comment by xcpky** [comment]
mic is still not working with the latest git
