### ISSUE TITLE
JSL UCM is missing

### ISSUE THREAD

**Issue by artkof86** [WeirdTreeThing/chromebook-linux-audio#24]
hello the script worked perfect on a gateway pirika chromebook but I formatted it with another linux distribution and now the script no longer works.

**Comment by artkof86** [comment]
Thanks for the support 

It used to work with any Linux distribution except debian and pop os .

**Comment by WeirdTreeThing** [comment]
> It used to work with any Linux distribution except debian and pop os .

Those distros need a custom kernel.

It probably stopped working because of a UCM update, jsl has never had that good of support.

**Comment by figuerom16** [comment]
Just tested my Magpie and the script on Pop OS which failed.
Worked perfectly with a fresh install of Endeavor OS.
Very happy with the results.  Thank you for your hard work!
