### ISSUE TITLE
Scripts don't work under opensuse tumbleweed

### ISSUE THREAD

**Issue by slimx** [WeirdTreeThing/chromebook-linux-audio#25]
It says can't install `linux-firmware`, maybe the real name is `kernel-firmware-all`.

**Comment by WeirdTreeThing** [comment]
Seems like I either missed this or opensuse changed something recently, either way it should work now.

**Comment by LZeugirdor** [comment]
> Seems like I either missed this or opensuse changed something recently, either way it should work now.

I had posted in the old eupnea issues about this, the -f option not existing. IDK what happened to that repo but I really appreciate this one, thank you.
