### ISSUE TITLE
error when running the setup code

### ISSUE THREAD

**Issue by mandy2315** [WeirdTreeThing/chromebook-linux-audio#28]
Hello, I am new to gallium os and Have been trying to run the setup code but I seem to run into an error for the switch statement. I assume this is because i am using the wrong version of python so I tried using a different version
output of pythong -V "python 2.7.17"
ouptut of python3 -V " python 3.6.9

here is the error error for "./setup-audio"
  File "./setup-audio", line 156
    match platform:
                 ^
SyntaxError: invalid syntax
I get the same error for "python3 setup-audio"

**Comment by WeirdTreeThing** [comment]
GalliumOS is not supported
