### ISSUE TITLE
Get audio to work with Zorin OS

### ISSUE THREAD

**Issue by TheEpicTen** [WeirdTreeThing/chromebook-linux-audio#29]
I am running Zorin OS Core 16.3 on a Lenovo 300e Chromebook (2nd Gen) and I'm trying to get audio to work. I have run the commands and get an error each time. I can't remember what the error is exactly, but if it's needed to help me work out what my problem is, I'll find out. I think it's probably something about "Other distros will likely work but will require you to manually install packages." I don't know how to do this! Help!

**Comment by ellyq** [comment]
https://chrultrabook.github.io/docs/docs/debugging.html#acpi-and-linux-kernelspace

**Comment by ninelore** [comment]
- If you use another distro the responsibility to find out how to manually install is solely yours
- We cant do anything without an error code lol, but you dont need to find out as its probably solved by above.

**Comment by dj1ch** [comment]
> 

The thing is, with zorin, the python version was outdated(python3.8). Your best bet is to compile it yourself and/or switch to another distro.

check this issue for more
[](https://forum.zorin.com/t/python-installation/13755)

**Comment by WeirdTreeThing** [comment]
You are on your own if you use Zorin.
