### ISSUE TITLE
Failed to install alsa-ucm-conf package on Fedora 38

### ISSUE THREAD

**Issue by SpeedPermitting** [WeirdTreeThing/chromebook-linux-audio#33]
My system:
Acer Chromebook R11 (C738T) (CYAN)
Platform: Intel Braswell
Linux fedora 6.4.15-200.fc38.x86_64

The following two lines were among the output from the setup-audio script on my system:

Error: Unable to find a match: alsa-ucm-conf
failed to run command: dnf install -y alsa-ucm-conf

I already had a package installed called "alsa-ucm", the version described here:
https://rpmfind.net/linux/RPM/fedora/updates/38/x86_64/Packages/a/alsa-ucm-1.2.10-2.fc38.noarch.html

Is this equivalent to the "alsa-ucm-conf" package available for other distros?

If so, perhaps the following change to line 201 in setup-audio would fix it?
FROM: 
`install_package("alsa-ucm-conf", "alsa-ucm-conf", "alsa-ucm-conf", "alsa-ucm-conf", "alsa-ucm-conf")`
TO: 
`install_package("alsa-ucm-conf", "alsa-ucm-conf", "alsa-ucm", "alsa-ucm-conf", "alsa-ucm-conf")`

Let me know if there's any other info I can provide that would be useful.

**Comment by WeirdTreeThing** [comment]
Fixed
