### ISSUE TITLE
Internal Mic doesn't show up in GNOME settings.

### ISSUE THREAD

**Issue by RayZGars** [WeirdTreeThing/chromebook-linux-audio#34]
Hi I used your script to install audio before I installed audio I already have speakers working so I installed the audio to get microphone working but it didn’t work help

**Comment by RayZGars** [comment]
Sorry It just said no Input Device on settings but on discord and other apps that need mic it detects and works.

**Comment by WeirdTreeThing** [comment]
Are you using GNOME?

**Comment by RayZGars** [comment]
Yes

**Comment by WeirdTreeThing** [comment]
I'm not sure why, but the mic doesn't show up sometimes in GNOME. It works just fine on any other DE though.

**Comment by WeirdTreeThing** [comment]
Seems like it doesn't set a default input device. Using pavucontrol to set a default one should fix it.
