### ISSUE TITLE
Debian 12 Pixel Slate (Nocturne) topology failed to load

### ISSUE THREAD

**Issue by Dulaithol** [WeirdTreeThing/chromebook-linux-audio#37]
All,

I currently have Debian 12 installed running (dual boot) using legacy boot on my Pixel Slate. And after following the steps and installing the custom kernel I'm still not able to see any media devices. I'm using version 6.1 kernel as I am running ZFS.

```
name@chromebook:~$ uname -a
Linux chromebook 6.1.27chrultrabook-fixups #8 SMP PREEMPT_DYNAMIC Sun Jun 25 01:43:38 BST 2023 x86_64 GNU/Linux
```

```
name@chromebook:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

[dmesg.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12795124/dmesg.txt)

Thanks

**Comment by WeirdTreeThing** [comment]
You need the [new kernel](https://tree123.org/chrultrabook/debian-kernel/linux-image-6.5.4-chrultrabook_6.5.4-1_amd64.deb).

**Comment by Dulaithol** [comment]
New kernel worked. All is good. 

Had a small hope that the older kernel would work so I didn't have to pull a newer version of ZFS.

**Comment by Dulaithol** [comment]
If you don't mind sharing what config is being used to create the kernel image? Is it stock Debian just with AVS included? Or is there more?

**Comment by WeirdTreeThing** [comment]
I believe I based it more on the ubuntu/popos config with all the AVS drivers enabled and maybe some other modifications.

**Comment by WeirdTreeThing** [comment]
@Dulaithol can I close this issue now?

**Comment by Dulaithol** [comment]
Yes, please. Thanks for the quick turnaround.
