### ISSUE TITLE
Microphone not picking up any sound on PHASER360 (Lenovo Chromebook 500e 2nd gen)

### ISSUE THREAD

**Issue by HyperNotZyper** [WeirdTreeThing/chromebook-linux-audio#4]
I'm running arch linux with kernel 6.3.6, using kde

**Comment by WeirdTreeThing** [comment]
In KDE audio aettings, allow going above 100% and set mic volume to 150%

**Comment by HyperNotZyper** [comment]
It works but its really quiet

**Comment by apandada1** [comment]
I have the same device running Kubuntu 23.04, and microphone works just fine. Did you try switching to "Pro Audio" and using the "Audio Pro 99" capture device? 
![image](https://github.com/WeirdTreeThing/chromebook-linux-audio/assets/3063132/dba0e3e5-37cd-4efb-be59-0056831373ab)

**Comment by WeirdTreeThing** [comment]
DO NOT use pro audio. Set mic level to 150% and it will work.
