### ISSUE TITLE
Asus C433T | Shyvana | Arch (based) Manjaro | HDMI + Headset = Y | Speakers = N

### ISSUE THREAD

**Issue by uhmzilighase** [WeirdTreeThing/chromebook-linux-audio#40]
[alsaucm.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12839596/alsaucm.txt)
[aplay_l.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12839597/aplay_l.txt)
[audio-debug.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12839598/audio-debug.log)
[dmesg.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12839599/dmesg.txt)
[sku.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12839600/sku.txt)

**Comment by WeirdTreeThing** [comment]
Update your kernel.

**Comment by uhmzilighase** [comment]
Sure enough. :-)
