### ISSUE TITLE
[Question] Using this utility with Other Custom Kernels on Debian-Based Distros

### ISSUE THREAD

**Issue by HeteroChromia420** [WeirdTreeThing/chromebook-linux-audio#44]
This is more of a question regarding compatibility with other Custom Kernels for Debian-Based Distributions (ie Xanmod/Liquorix), would this utility work for those?

**Comment by HeteroChromia420** [comment]
Following up from this, i haven't had much success with the liquorix kernel, but xanmod seems to work fine. Maybe the issue is on my end, but since xanmod works, i'll stick with that i suppose...

**Comment by WeirdTreeThing** [comment]
For anyone else reading this, I'd stick to distro kernels or custom kernels provided by the chrultrabook project, but feel free to experiment. If they work, good for you. If they don't, nothing I can do about that.
