### ISSUE TITLE
no sound on barla chromebook

### ISSUE THREAD

**Issue by thebestofall007** [WeirdTreeThing/chromebook-linux-audio#46]
I ran your script but still no sound on hp chromebook with amd stoneyridge processor, codename barla. I upgraded to the latest coreboot from mrchromebox.tech as well. I am running pop os 22.04.  Am I missing anything?

**Comment by WeirdTreeThing** [comment]
You need a [custom kernel](https://fs.nightcore.monster/chromebook/stoney/kernel/archive/linux-stoney-6.5.6-20231006-1355.tar.xz).

**Comment by thebestofall007** [comment]
ok, how do I install this?

**Comment by WeirdTreeThing** [comment]
depends on your distro

**Comment by thebestofall007** [comment]
I'm using pop is, which is based on Ubuntu 22.04.

**Comment by WeirdTreeThing** [comment]
This is not the place to ask for help installing a custom kernel.
