### ISSUE TITLE
Device events isn't recognized by ALSA / audio servers.

### ISSUE THREAD

**Issue by GamePlayer-8** [WeirdTreeThing/chromebook-linux-audio#49]
Good evening,

There are several issues towards:
 - recognizing if headphones has a microphone;
 - recognizing if headphones are unplugged;
 - recognizing `Digital Surround` options for audio device(s).

on driver `snd_soc_acp_da7219mx98357` used in Chromebook `HP 11A G6 EE`.
OS is Artix Linux with custom kernel provided by Chrultrabook.

**Comment by WeirdTreeThing** [comment]
kernel version?

**Comment by GamePlayer-8** [comment]
`6.4.16`

**Comment by WeirdTreeThing** [comment]
https://patchwork.kernel.org/project/alsa-devel/list/?series=772289&state=*
https://patchwork.kernel.org/project/alsa-devel/patch/20230818080314.32991-1-alpernebiyasak@gmail.com/

**Comment by GamePlayer-8** [comment]
how do I apply those patches on `6.4.16` kernel?

**Comment by WeirdTreeThing** [comment]
You should only need to apply the ones related to AMD/ACP.

**Comment by GamePlayer-8** [comment]
Last patch had issues at line 792 and 851. I've removed those and compiled the kernel, but still no change in the Audio section.

**Comment by WeirdTreeThing** [comment]
Unsure then, I'm using a patched 6.6 kernel here and jack detection works for me.

**Comment by GamePlayer-8** [comment]
Update: jack switching between headphones and speakers works along with headphones microphone detection after re-running the audio fix script.

Still audio servers recognize it as just `Default` without any special option for `Digital Surround`.

**Comment by WeirdTreeThing** [comment]
Why would surround be a option? The `Default` profile is defined by ucm.

**Comment by GamePlayer-8** [comment]
I realized, I can rewrite it with audio server config manually - I'll close the issue as solved.
