### ISSUE TITLE
Support for "pujjoflex"

### ISSUE THREAD

**Issue by nandotabr** [WeirdTreeThing/chromebook-linux-audio#50]
Hi, will there be audio support for "pujjoflex" or the Lenovo Flex 3i Chromebook? Thanks!

**Comment by WeirdTreeThing** [comment]
I'm doing some major rework for the UCM currently, I should be able to get it done within a few days or so.

**Comment by nandotabr** [comment]
thank you @WeirdTreeThing

**Comment by WeirdTreeThing** [comment]
Try `./setup-audio --branch common-codecs` and let me know how it works. HDMI won't work for now but the rest should work.

**Comment by nandotabr** [comment]
Hi @WeirdTreeThing - this the outcome of running the script:

penguin:~/chromebook-linux-audio$ ./setup-audio --branch common-codecs
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
**Unknown/Unsupported chromebook model: pujjo**

Also tried overriding the board name with "pujjoflex":

penguin:~/chromebook-linux-audio$ ./setup-audio -b pujjoflex --branch common-codecs 
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Board name override: pujjoflex
**Unknown/Unsupported chromebook model: pujjoflex**

**Comment by WeirdTreeThing** [comment]
Sorry, I forgot to mention that I don't have your board in the list of supported ones currently. You can override to any ADL board, like `osiris` for example.

**Comment by nandotabr** [comment]
Thank you @WeirdTreeThing - it says "Audio installed successfully" and I see that the new kernel is there however there is still no sound and the audio card is not showing in pavucontrol even after rebooting. Should I try a different board?

**Comment by WeirdTreeThing** [comment]
Run the debugging script and send logs https://chrultrabook.github.io/docs/docs/debugging.html#acpi-and-linux-kernelspace

**Comment by nandotabr** [comment]
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13453422/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
It didn't generate an audio log for some reason. Can you send the output of `pactl info`.
