### ISSUE TITLE
Fedora 39 test

### ISSUE THREAD

**Issue by gxsw** [WeirdTreeThing/chromebook-linux-audio#51]
Hi! sound is working fine on my kano (rpl) in archlinux.
As Fedora 39 was just released I wanted to try it. The script ran successfully but there is no sound after reboot.
 logs:
[debug-logs.zip](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13298718/debug-logs.zip)

**Comment by WeirdTreeThing** [comment]
`ls /lib/firmware/intel/sof-tplg`

**Comment by gxsw** [comment]
@fedora:~$ ls /lib/firmware/intel/sof-tplg
sof-acp.tplg.xz
sof-adl-cs35l41.tplg.xz
sof-adl-es8336-dmic2ch-ssp0.tplg.xz
sof-adl-es8336-dmic2ch-ssp1.tplg.xz
sof-adl-es8336-dmic2ch-ssp2.tplg.xz
sof-adl-es8336-dmic4ch-ssp0.tplg.xz
sof-adl-es8336-dmic4ch-ssp1.tplg.xz
sof-adl-es8336-dmic4ch-ssp2.tplg.xz
sof-adl-es8336-ssp0.tplg.xz
sof-adl-es8336-ssp1-hdmi-ssp02.tplg.xz
sof-adl-es8336-ssp1.tplg.xz
sof-adl-es8336-ssp2.tplg.xz
sof-adl-es8336.tplg.xz
sof-adl-max98357a-rt5682-2way.tplg.xz
sof-adl-max98357a-rt5682-4ch.tplg.xz
sof-adl-max98357a-rt5682-rtnr.tplg.xz
sof-adl-max98357a-rt5682.tplg.xz
sof-adl-max98357a-rt5682-waves-2way.tplg.xz
sof-adl-max98357a-rt5682-waves.tplg.xz
sof-adl-max98360a-nau8825.tplg.xz
sof-adl-max98360a-rt5682-2way.tplg.xz
sof-adl-max98360a-rt5682-4ch.tplg.xz
sof-adl-max98360a-rt5682-rtnr.tplg.xz
sof-adl-max98360a-rt5682.tplg.xz
sof-adl-max98360a-rt5682-waves.tplg.xz
sof-adl-max98373-nau8825-dts.tplg.xz
sof-adl-max98373-nau8825.tplg.xz
sof-adl-max98390-rt5682-google-aec.tplg.xz
sof-adl-max98390-rt5682-rtnr.tplg.xz
sof-adl-max98390-rt5682.tplg.xz
sof-adl-max98390-ssp2-rt5682-ssp0.tplg.xz
sof-adl-nau8825.tplg.xz
sof-adl-nocodec-ci.tplg.xz
sof-adl-nocodec-hdmi-ssp02.tplg.xz
sof-adl-nocodec.tplg.xz
sof-adl-rt1015-nau8825.tplg.xz
sof-adl-rt1019-nau8825.tplg.xz
sof-adl-rt1019-rt5682.tplg.xz
sof-adl-rt1316-l12-rt714-l0.tplg.xz
sof-adl-rt1316-l1-mono-rt714-l0.tplg.xz
sof-adl-rt1316-l2-mono-rt714-l0.tplg.xz
sof-adl-rt1316-l2-mono-rt714-l3.tplg.xz
sof-adl-rt5682.tplg.xz
sof-adl-rt711-4ch.tplg.xz
sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg.xz
sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg.xz
sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg.xz
sof-adl-rt711-l0-rt1316-l2-2ch.tplg.xz
sof-adl-rt711-l0-rt1316-l2-4ch.tplg.xz
sof-adl-rt711-l0-rt1316-l3-2ch.tplg.xz
sof-adl-rt711-l2-rt1316-l01-rt714-l3.tplg.xz
sof-adl-rt711-l2-rt1316-l01.tplg.xz
sof-adl-rt711.tplg.xz
sof-adl-sdw-max98373-rt5682.tplg.xz
sof-apl-da7219.tplg.xz
sof-apl-demux-pcm512x.tplg.xz
sof-apl-es8336-dmic2ch-ssp0.tplg.xz
sof-apl-es8336-dmic2ch-ssp1.tplg.xz
sof-apl-es8336-dmic2ch-ssp2.tplg.xz
sof-apl-es8336-dmic2ch-ssp5.tplg.xz
sof-apl-es8336-dmic4ch-ssp0.tplg.xz
sof-apl-es8336-dmic4ch-ssp1.tplg.xz
sof-apl-es8336-dmic4ch-ssp2.tplg.xz
sof-apl-es8336-dmic4ch-ssp5.tplg.xz
sof-apl-es8336-ssp0.tplg.xz
sof-apl-es8336-ssp1.tplg.xz
sof-apl-es8336-ssp2.tplg.xz
sof-apl-es8336-ssp5.tplg.xz
sof-apl-es8336.tplg.xz
sof-apl-keyword-detect.tplg.xz
sof-apl-nocodec-ci.tplg.xz
sof-apl-nocodec.tplg.xz
sof-apl-pcm512x-master-44100.tplg.xz
sof-apl-pcm512x-master.tplg.xz
sof-apl-pcm512x.tplg.xz
sof-apl-rt298.tplg.xz
sof-apl-tdf8532.tplg.xz
sof-apl-wm8804.tplg.xz
sof-bdw-nocodec.tplg.xz
sof-bdw-rt286.tplg.xz
sof-bdw-rt5640.tplg.xz
sof-bdw-rt5677.tplg.xz
sof-byt-cx2072x-ssp0.tplg.xz
sof-byt-cx2072x.tplg.xz
sof-byt-da7213-ssp0.tplg.xz
sof-byt-da7213.tplg.xz
sof-byt-es8316-ssp0.tplg.xz
sof-byt-es8316.tplg.xz
sof-byt-max98090.tplg.xz
sof-byt-nocodec.tplg.xz
sof-byt-rt5640-ssp0.tplg.xz
sof-byt-rt5640.tplg.xz
sof-byt-rt5645-ssp0.tplg.xz
sof-byt-rt5645.tplg.xz
sof-byt-rt5651-ssp0.tplg.xz
sof-byt-rt5651.tplg.xz
sof-byt-rt5670-ssp0.tplg.xz
sof-byt-rt5670.tplg.xz
sof-byt-rt5682-ssp0.tplg.xz
sof-byt-rt5682.tplg.xz
sof-byt-wm5102-ssp0.tplg.xz
sof-cht-cx2072x.tplg.xz
sof-cht-da7213.tplg.xz
sof-cht-es8316.tplg.xz
sof-cht-max98090.tplg.xz
sof-cht-nau8824.tplg.xz
sof-cht-nocodec.tplg.xz
sof-cht-rt5640.tplg.xz
sof-cht-rt5645.tplg.xz
sof-cht-rt5651.tplg.xz
sof-cht-rt5670.tplg.xz
sof-cht-rt5682.tplg.xz
sof-cml-da7219-max98357a.tplg.xz
sof-cml-da7219-max98390.tplg.xz
sof-cml-demux-rt5682-max98357a.tplg.xz
sof-cml-demux-rt5682.tplg.xz
sof-cml-es8336-dmic2ch-ssp0.tplg.xz
sof-cml-es8336-dmic2ch-ssp1.tplg.xz
sof-cml-es8336-dmic2ch-ssp2.tplg.xz
sof-cml-es8336-dmic4ch-ssp0.tplg.xz
sof-cml-es8336-dmic4ch-ssp1.tplg.xz
sof-cml-es8336-dmic4ch-ssp2.tplg.xz
sof-cml-es8336-ssp0.tplg.xz
sof-cml-es8336-ssp1.tplg.xz
sof-cml-es8336-ssp2.tplg.xz
sof-cml-nocodec.tplg.xz
sof-cml-rt1011-rt5682.tplg.xz
sof-cml-rt5682-kwd.tplg.xz
sof-cml-rt5682-max98357a.tplg.xz
sof-cml-rt5682.tplg.xz
sof-cml-rt700-2ch.tplg.xz
sof-cml-rt700-4ch.tplg.xz
sof-cml-rt700.tplg.xz
sof-cml-rt711-rt1308-mono-rt715.tplg.xz
sof-cml-rt711-rt1308-rt715.tplg.xz
sof-cnl-nocodec.tplg.xz
sof-cnl-rt274.tplg.xz
sof-ehl-nocodec.tplg.xz
sof-ehl-rt5660-nohdmi.tplg.xz
sof-ehl-rt5660.tplg.xz
sof-glk-cs42l42.tplg.xz
sof-glk-da7219-kwd.tplg.xz
sof-glk-da7219.tplg.xz
sof-glk-es8336-dmic2ch-ssp0.tplg.xz
sof-glk-es8336-dmic2ch-ssp1.tplg.xz
sof-glk-es8336-dmic2ch-ssp2.tplg.xz
sof-glk-es8336-dmic2ch-ssp5.tplg.xz
sof-glk-es8336-dmic4ch-ssp0.tplg.xz
sof-glk-es8336-dmic4ch-ssp1.tplg.xz
sof-glk-es8336-dmic4ch-ssp2.tplg.xz
sof-glk-es8336-dmic4ch-ssp5.tplg.xz
sof-glk-es8336-ssp0.tplg.xz
sof-glk-es8336-ssp1.tplg.xz
sof-glk-es8336-ssp2.tplg.xz
sof-glk-es8336-ssp5.tplg.xz
sof-glk-es8336.tplg.xz
sof-glk-nocodec.tplg.xz
sof-glk-rt5682.tplg.xz
sof-hda-generic-1ch-pdm1.tplg.xz
sof-hda-generic-1ch.tplg.xz
sof-hda-generic-2ch-kwd.tplg.xz
sof-hda-generic-2ch-pdm1.tplg.xz
sof-hda-generic-2ch.tplg.xz
sof-hda-generic-3ch.tplg.xz
sof-hda-generic-4ch-kwd.tplg.xz
sof-hda-generic-4ch.tplg.xz
sof-hda-generic-idisp-2ch.tplg.xz
sof-hda-generic-idisp-4ch.tplg.xz
sof-hda-generic-idisp.tplg.xz
sof-hda-generic.tplg.xz
sof-icl-dmic-4ch.tplg.xz
sof-icl-es8336-dmic2ch-ssp0.tplg.xz
sof-icl-es8336-dmic2ch-ssp1.tplg.xz
sof-icl-es8336-dmic2ch-ssp2.tplg.xz
sof-icl-es8336-dmic4ch-ssp0.tplg.xz
sof-icl-es8336-dmic4ch-ssp1.tplg.xz
sof-icl-es8336-dmic4ch-ssp2.tplg.xz
sof-icl-es8336-ssp0.tplg.xz
sof-icl-es8336-ssp1.tplg.xz
sof-icl-es8336-ssp2.tplg.xz
sof-icl-nocodec.tplg.xz
sof-icl-rt5682-kwd.tplg.xz
sof-icl-rt5682.tplg.xz
sof-icl-rt700-2ch.tplg.xz
sof-icl-rt700-4ch.tplg.xz
sof-icl-rt700.tplg.xz
sof-icl-rt711-rt1308-rt715.tplg.xz
sof-jsl-cs42l42-mx98360a.tplg.xz
sof-jsl-da7219-mx98360a.tplg.xz
sof-jsl-da7219.tplg.xz
sof-jsl-es8336-dmic2ch-ssp0.tplg.xz
sof-jsl-es8336-dmic2ch-ssp1.tplg.xz
sof-jsl-es8336-dmic2ch-ssp2.tplg.xz
sof-jsl-es8336-dmic4ch-ssp0.tplg.xz
sof-jsl-es8336-dmic4ch-ssp1.tplg.xz
sof-jsl-es8336-dmic4ch-ssp2.tplg.xz
sof-jsl-es8336-ssp0.tplg.xz
sof-jsl-es8336-ssp1.tplg.xz
sof-jsl-es8336-ssp2.tplg.xz
sof-jsl-nocodec.tplg.xz
sof-jsl-rt5682-mx98360a.tplg.xz
sof-jsl-rt5682-rt1015.tplg.xz
sof-jsl-rt5682-rt1015-xperi.tplg.xz
sof-jsl-rt5682.tplg.xz
sof-rn-rt5682-max98360.tplg.xz
sof-rn-rt5682-rt1019.tplg.xz
sof-rpl-nocodec.tplg.xz
sof-rpl-rt1316-l12-rt714-l0.tplg.xz
sof-rpl-rt711-4ch.tplg.xz
sof-rpl-rt711-l0-rt1316-l12-rt714-l3.tplg.xz
sof-rpl-rt711-l0-rt1318-l12-rt714-l3.tplg.xz
sof-rpl-rt711-l0-rt1318-l12.tplg.xz
sof-rpl-rt711-l0.tplg.xz
sof-rpl-rt711-l2-rt1316-l01-rt714-l3.tplg.xz
sof-rpl-rt711-l2-rt1316-l01.tplg.xz
sof-rpl-rt711-l2.tplg.xz
sof-rpl-rt711.tplg.xz
sof-smart-amplifier-nocodec.tplg.xz
sof-tgl-es8336-dmic2ch-ssp0.tplg.xz
sof-tgl-es8336-dmic2ch-ssp1.tplg.xz
sof-tgl-es8336-dmic2ch-ssp2.tplg.xz
sof-tgl-es8336-dmic4ch-ssp0.tplg.xz
sof-tgl-es8336-dmic4ch-ssp1.tplg.xz
sof-tgl-es8336-dmic4ch-ssp2.tplg.xz
sof-tgl-es8336-ssp0.tplg.xz
sof-tgl-es8336-ssp1.tplg.xz
sof-tgl-es8336-ssp2.tplg.xz
sof-tgl-es8336.tplg.xz
sof-tgl-h-nocodec.tplg.xz
sof-tgl-max98357a-rt5682-pdm1-drceq.tplg.xz
sof-tgl-max98357a-rt5682-pdm1-google-aec.tplg.xz
sof-tgl-max98357a-rt5682-pdm1.tplg.xz
sof-tgl-max98357a-rt5682-rtnr.tplg.xz
sof-tgl-max98357a-rt5682.tplg.xz
sof-tgl-max98373-rt5682-igonr.tplg.xz
sof-tgl-max98373-rt5682.tplg.xz
sof-tgl-max98373-rt5682-xperi.tplg.xz
sof-tgl-nocodec-ci.tplg.xz
sof-tgl-nocodec-hdmi-ssp15.tplg.xz
sof-tgl-nocodec.tplg.xz
sof-tgl-rt1011-rt5682.tplg.xz
sof-tgl-rt1308-ssp2-hdmi-ssp15.tplg.xz
sof-tgl-rt5682-ssp0-max98373-ssp2.tplg.xz
sof-tgl-rt5682-ssp0-max98373-ssp2-xperi.tplg.xz
sof-tgl-rt711-4ch.tplg.xz
sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg.xz
sof-tgl-rt711-rt1308-2ch.tplg.xz
sof-tgl-rt711-rt1308-4ch.tplg.xz
sof-tgl-rt711-rt1308-mono-rt715.tplg.xz
sof-tgl-rt711-rt1308-rt715.tplg.xz
sof-tgl-rt711-rt1316-rt714.tplg.xz
sof-tgl-rt715-rt711-rt1308-mono.tplg.xz
sof-tgl-sdw-max98373-rt5682.tplg.xz
sof-whl-demux-rt5682.tplg.xz
sof-whl-rt5682-kwd.tplg.xz
sof-whl-rt5682.tplg.xz
@fedora:~$

**Comment by WeirdTreeThing** [comment]
I see, fedora decided to make things more difficult by compressing the tplg files.

**Comment by WeirdTreeThing** [comment]
Try the script again.

**Comment by gxsw** [comment]
Thx! It is working now in Fedora 39! :)
