### ISSUE TITLE
AVS installed on what should be max98357a - how to uninstall?

### ISSUE THREAD

**Issue by askiiart** [WeirdTreeThing/chromebook-linux-audio#58]
**Describe the bug**
I have an Asus C433, which according to the [Chultrabook supported devices list](https://chrultrabook.github.io/docs/docs/supported-devices.html) has a max98357a. Additionally, I believe that I was able to install the audio driver in "max983357a mode" before reinstalling Linux, but after reinstalling I've been configuring i3 for hours, so it's all turned into a bit of a blur. Regardless, the AVS driver was still installed.

**Boardname**
Shyvana

**Logs**
Please add a note to your template that it's saved in `~/Desktop`, I had to use `find` to find the file.

[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13402578/debug-logs.tar.gz)

The code seems to check if `/sys/bus/acpi/devices/MX98357A:00` exists to see if the device has a max98357a. That does not exist on my computer, instead I have `/sys/bus/acpi/devices/MX98927:00`. Before going any further, I'd like to uninstall the driver, just to be safe. So how would I do that?

P.S. I'm going to try some live USBs to see if any of those have `MX98357A:00`, will keep you updated.

**Comment by askiiart** [comment]
Actually, correction: I'm not rebooting at all until I have the driver uninstalled. Wouldn't want to risk losing my speakers. Once that's uninstalled I'll give some live USBs a try to figure out what's up with this weirdness.

**Comment by WeirdTreeThing** [comment]
Shyvana has max98927, not max88357a. Your speakers are fine. Even if you had max98357a, they don't just spontaneously explode. You need to be playing fairly loud audio for any damage to occur.

**Comment by askiiart** [comment]
> Shyvana has max98927, not max98357a. Your speakers are fine. Even if you had max98357a, they don't just spontaneously explode. You need to be playing fairly loud audio for any damage to occur.

Okay, thank you! I think Chrultrabook has a bug in how the docs are generated.
