### ISSUE TITLE
Acer Spin 13 (akali360) microphone issues PopOS

### ISSUE THREAD

**Issue by sh0dZz** [WeirdTreeThing/chromebook-linux-audio#59]
The microphone doesn't show up anywhere, not even in pavucontrol. I checked discord to see whether it shows up and it did, but the name seemed like a device address of some type (?)
My speakers do show up and work properly. My OS is PopOS!

**Boardname**
Akali 360

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13452140/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Try the testing branch, `./setup-audio --branch common-codecs`.

**Comment by WeirdTreeThing** [comment]
Looks like stock firmware is broken (unsurpriringly).
