### ISSUE TITLE
I Tested audio in Some OSes in Chromebook 14 (LARS) Skylake 

### ISSUE THREAD

**Issue by elKawai628** [WeirdTreeThing/chromebook-linux-audio#6]
**UEFI moment lmao**

```
PopOS: Works but buggy
Ubuntu 22.04 [Jammy]: No worky :c
Ubuntu 23.04 [Lunar]: Audio fails successfully (i mean , audio cards works and everything fine , the problem here its pulseaudio :c)
Fedora: Works with a very little issue that is not bad and it can be ignored until new script update

```
send help

**Comment by WeirdTreeThing** [comment]
Almost like the README says that Ubuntu has issues. PopOS should work though so not sure about that.

**Comment by elKawai628** [comment]
ik frfr

**Comment by WeirdTreeThing** [comment]
Are you going to provide anything useful for debugging? You never even said what was wrong.

**Comment by elKawai628** [comment]
wait hold up, Audio Doesn't work in Fedora 38
i mean happends the same as in ubuntu 23
(audio cards work but it has pulseaudio errors)
![image](https://github.com/WeirdTreeThing/chromebook-linux-audio/assets/131639764/116122d7-a3f3-4323-9948-54f1b4cff82d)

**Comment by WeirdTreeThing** [comment]
`pulseaudio -v &> pulseaudio.txt`

**Comment by elKawai628** [comment]
thats something for getting a log?
i mean because that did anything

**Comment by WeirdTreeThing** [comment]
`systemctl --user stop pulseaudio.socket`

**Comment by elKawai628** [comment]
nothing happend

**Comment by WeirdTreeThing** [comment]
run the puslseaudio command again

**Comment by elKawai628** [comment]
```
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.

```

**Comment by elKawai628** [comment]
im going to upgrade packages give me a second

**Comment by WeirdTreeThing** [comment]
Huh, weird.
```
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
pulseaudio -v &> pulseaudio.txt
```

**Comment by elKawai628** [comment]
oh nevermind , i did something and the funy audio just get working

**Comment by WeirdTreeThing** [comment]
Oh ok then.
