### ISSUE TITLE
APL Audio fixed in Intel's 5.19 driver?

### ISSUE THREAD

**Issue by RodBarnes** [WeirdTreeThing/chromebook-linux-audio#60]
Not an issue but a question since Discussions aren't enabled in this repository.  Do you know whether the upgraded [Intel driver for AVS](https://www.phoronix.com/news/Linux-5.19-Sound) will resolve the lack of volume limiter of max98357a on AVS?

**Comment by WeirdTreeThing** [comment]
We are using the AVS driver, which is the one with the problem. The SKL driver also had the same problem but it never worked properly on modern kernel versions(5.4+).

**Comment by RodBarnes** [comment]
Thanks. I take your response to mean that the AVS made available by your repository is the same as what is rolled into the 5.19 kernel.

**Comment by WeirdTreeThing** [comment]
AVS didn't fully land until 6.0, but there have been many updates to it so the minimum supported kernel version is now 6.4 if you want to use my script.

**Comment by RodBarnes** [comment]
Got it. Let's question on this (I think): Is the lack-of-volume-limiter an issue with AVS or is it inherent in the hardware?

**Comment by WeirdTreeThing** [comment]
Sorta both. Google is using cheap speaker amps on these devices, which don't have any feedback protection. So instead, software is used to limit the maximum audio output. There is something wrong with the AVS (and older SKL) driver that makes the left channel heat up faster than the right channel, causing damage. SOF doesn't have this problem.
