### ISSUE TITLE
Audio cracking/popping on Lenovo ThinkPad C13 Yoga

### ISSUE THREAD

**Issue by biribas** [WeirdTreeThing/chromebook-linux-audio#62]
The computer plays the audio, but there is a constant background noise of cracking/popping

Boardname: Morphius
Operating System: Fedora Linux 39

Logs: [cbmem.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13478530/cbmem.tar.gz)

**Comment by WeirdTreeThing** [comment]
Do you have `iommu=pt` in your cmdline?

**Comment by biribas** [comment]
Yes, I followed [this](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html/installation_guide/appe-configuring_a_hypervisor_host_for_pci_passthrough) guide to do that.

**Comment by WeirdTreeThing** [comment]
Can you send dmesg?

**Comment by biribas** [comment]
[output.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13481856/output.txt)

**Comment by WeirdTreeThing** [comment]
Not seeing anything wrong there. Two things you can try: older like (like LTS) or switching audio server (pipewire <-> pulse).

**Comment by biribas** [comment]
I just tested both possibilites and none of them work. I believe it is not an incompatibility related to the kernel or audio server. 

I also noticed a pattern in the audio error. When I play an audio, it works perfectly for 1 or 2 seconds before pausing momentarily. After this, the audio returns, but it starts to crackle. This occurs in both speakers and headphones.

Facts I noticed when doing some tests:
- The audio only crackles on speakers and wired headphones; the audio is perfectly clean on bluetooth headphones;
- When I share my computer's audio with another device via RTSP, the computer's audio (magically) stops crackling instantly. Once the RTSP connection is broken, the popping occurs again.

**Comment by WeirdTreeThing** [comment]
Interesting. I'll be getting a Vilboz in a few days so I'll see if I can reproduce when I get it.

**Comment by biribas** [comment]
Udpate: I noticed that, in reality, the audio is only corrected when the microphone is active. The audio was corrected during the RTSP connection because it activated the microphone. I hope this new information can be useful to you in understanding the reason for the error.

**Comment by WeirdTreeThing** [comment]
Interesting, I'll see when Vilboz arrives (monday or tuesday).

**Comment by thinkpadworship** [comment]
Any updates on this? I have a similar issue. Audio will also speed up on YouTube after a couple of seconds of playback and start cutting/popping.

**Comment by WeirdTreeThing** [comment]
Sorry, I forgot about this issue. I can test my Vilboz soon.

**Comment by WeirdTreeThing** [comment]
I was able to reproduce the speed issues. Funny though that opening the kde sound applet will cause it to start recording the internal mic, which fixes the issue as OP said.

**Comment by WeirdTreeThing** [comment]
See: https://forum.chrultrabook.com/t/morphius-audio-popping-in-firefox-you-may-need-this-pipewire-patch/717

**Comment by thinkpadworship** [comment]
> See: https://forum.chrultrabook.com/t/morphius-audio-popping-in-firefox-you-may-need-this-pipewire-patch/717

Thanks, I updated my system and everything was solved straight away. Thanks for all of your work on this project!

**Comment by biribas** [comment]
Same here, thanks!
