### ISSUE TITLE
C434 Shyvana, mrchromebox UEFI, Pop!OS 22.04. No sound after running script

### ISSUE THREAD

**Issue by DoughMucker** [WeirdTreeThing/chromebook-linux-audio#64]
Hi, I've run your script on a C434 Shyvana, mrchromebox UEFI, with Pop!OS 22.04 but get no sound after rebooting. Sound output device still shows "Dummy Output" 

**Boardname**
Shyvana

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13553775/debug-logs.tar.gz)

Sound is the last hurdle I'm trying to overcome to make this into a nice laptop. I'm hoping it can work.

Thanks,
Doug

**Comment by WeirdTreeThing** [comment]
It looks like PopOS doesn't have avs_max98927 enabled in their kernel, which is needed for speakers on your device. You can try installing the [debian kernel](https://ethanthesleepy.one/public/chrultrabook/debian-kernel/linux-image-6.6.0-chrultrabook_6.6.0-2_amd64.deb).

**Comment by DoughMucker** [comment]
Thank you!! That was really easy. Thank you for your help and the script.
