### ISSUE TITLE
Audio gone in Debian 12.3

### ISSUE THREAD

**Issue by jeroen-80** [WeirdTreeThing/chromebook-linux-audio#66]
Sound worked in bookworm. Performed upgrade to 12.3: sound gone. Re-install with latest source doesn't fix the issue: only the dummy hardware is detected.

System = edgar.
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13664052/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
You seem to be using the default debian kernel, which is often missing sound drivers for chromebooks. The script should prompt you to install the chrultrabook kernel.
