### ISSUE TITLE
SONA, audio support status.   Fedora 38 KDE

### ISSUE THREAD

**Issue by tornadox** [WeirdTreeThing/chromebook-linux-audio#7]
Hi @WeirdTreeThing  I've gone UEFI Fedora 38 KDE (6.3), board SONA HP Chromebook 14 x360, when I install audio I get the following.

Laptop
Working microphone only (I haven't tested though)

3.5" Jack
Earphone and Microphone work
(tested mic as well)

HDMI
I don't remember if I tested before or after installing, but I didn't have HDMI audio.

Please let me know if I should expect anything else to work or be fixed in the future. 

What is post-install compatibility? Will it survive upgrades etc? How can I update to get the latest version when new fixes are available?

**Comment by WeirdTreeThing** [comment]
> Working microphone only (I haven't tested though)

I assume you mean speakers don't work. Did you read the warnings that said it wouldn't work unless you ran it with a specific command line option?

> I don't remember if I tested before or after installing, but I didn't have HDMI audio.

Send dmesg.

> What is post-install compatibility? Will it survive upgrades etc? How can I update to get the latest version when new fixes are available?

The files this script installs shouldn't be touched at all by your package manager. To get the latest fixes, run the script again.

**Comment by tornadox** [comment]
THANKS!!!! Speakers work now, actually, at 100% all is fine. But I'm comfortable with 50-70% 

> I assume you mean speakers don't work. Did you read the warnings that said it wouldn't work unless you ran it with a specific command line option?

When I was on depthboot only chrome os kernel worked and this option did nothing at that time so I forgot about it.

HDMI Audio still doesn't, not a huge issue now, attaching both dmesg files.
[dmesg before script.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/11819510/dmesg.before.script.txt)
[dmesg after script.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/11819511/dmesg.after.script.txt)

**Comment by WeirdTreeThing** [comment]
> HDMI Audio still doesn't, not a huge issue now, attaching both dmesg files.

`ls /lib/firmware/intel/avs`

**Comment by tornadox** [comment]
```
$ ls /lib/firmware/intel/avs
apl  da7219-tplg.bin  hda-80862809-tplg.bin  max98357a-tplg.bin  max98927-tplg.bin  skl
cnl  dmic-tplg.bin    hda-8086280a-tplg.bin  max98373-tplg.bin   nau8825-tplg.bin   ssm4567-tplg.bin
```
btw it seem to be similar to https://github.com/eupnea-linux/audio-scripts/issues/63

**Comment by WeirdTreeThing** [comment]
Did you just recently run the script? You are missing a lot of topology files.

**Comment by tornadox** [comment]
apparently I downloaded the old repo by mistake
current output and I have HDMI sound (3 devices)
```
[tornadox@chromebook ~]$ ls /lib/firmware/intel/avs
apl              dmic-tplg.bin          hda-8086280b-tplg.bin  hda-8086280f-tplg.bin  max98373-tplg.bin  skl
cnl              hda-80862809-tplg.bin  hda-8086280c-tplg.bin  hda-8086281a-tplg.bin  max98927-tplg.bin  ssm4567-tplg.bin
da7219-tplg.bin  hda-8086280a-tplg.bin  hda-8086280d-tplg.bin  max98357a-tplg.bin     nau8825-tplg.bin
```
but during switching sources (sound level 30%, I heard crackling noises from the laptop speaker and I suppose some burnt smell, rebooted, and the speaker works so far.

**Comment by tornadox** [comment]
> Well when you had the volume higher earlier, it could have caused some damage.

I've kept all at 30%, and even on level 100% I don't hear an overdrive from the speakers, anyway if the speakers (and not the amp) get burned I'll replace them. Not an issue. Ok, closing. Thanks for your help!
