### ISSUE TITLE
lubuntu audio 

### ISSUE THREAD

**Issue by Wildtick** [WeirdTreeThing/chromebook-linux-audio#71]
since this isn't really a bug but have you tested lubuntu on this or is it the same as normal ubuntu?

**Comment by WeirdTreeThing** [comment]
As long as you stick to the latest release, it should work like normal.

**Comment by Wildtick** [comment]
i have 22.04.3 is that good?

**Comment by WeirdTreeThing** [comment]
you want 23.10
