### ISSUE TITLE
Prompt Debian users with AVS audio to install custom kernel first

### ISSUE THREAD

**Issue by Catbirby** [WeirdTreeThing/chromebook-linux-audio#72]
When you have a device that has both avs audio and Debian installed, the script will give you the avs error: "Looks like your kernel doesn't have the avs modules. Make sure you are on at least 6.0 with avs enabled." It never asks if you want to install the required custom Debian kernel that has the avs modules enabled.

**Comment by mrwm** [comment]
Current debian kernels can be found at `https://tree123.org/chrultrabook/debian-kernel/`. I found the link through the pinned github issues.

At the time of this writing, the current kernel is here:

- https://tree123.org/chrultrabook/debian-kernel/linux-image-6.6.0-chrultrabook_6.6.0-2_amd64.deb
