### ISSUE TITLE
Acer CB315-2H AMD  ALEENA Mrchromebox firmware, dummy output only in Linux mint 21.2 kernel 6.5.0-14 and Fedora 39

### ISSUE THREAD

**Issue by fargodwe** [WeirdTreeThing/chromebook-linux-audio#74]
Acer Chromebook CB315-2H  AMD A4 , latest mrchromebox firmware.  Haven't had sound in Linux Mint.  Installed 21.2 and kernel 6.5.0-14 and tried Fedora 39.  Just shows dummy output.
 
Boardname:  Aleena

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.

*******  The above aborted saying lspci not found and to install pci-utils, yet pci-utils is installed.

**Comment by WeirdTreeThing** [comment]
You need a custom kernel. Prebuilt kernel is at https://fs.nightcore.monster/chromebook/stoney/kernel/latest.tar.xz.

**Comment by fargodwe** [comment]
Thank you for the quick reply!!   

I wasn't sure what to do with what downloaded after I extracted it.  After looking in linux Mint's /boot I ended up copying the vmlinuz and system map to /boot, ran update-grub, rebooted and selected the new kernel.  It wouldn't boot - just went to a blank (but backlit) screen.  I then tried again, adding nomodeset in case there was some problem with the amdgpu drivers.  Went further - got back to the jackrabbit screen but then never progressed beyond that.  I know that Mint is always "behind" so I don't know if that has something to do with it.  I really don't know enough about any of this but to be a mess waiting to happen :)  Should I try the same with Fedora?

Thanks so much!

**Comment by WeirdTreeThing** [comment]
inside the modules dir, there should be lib/modules/<kernel ver>. You need to copy that kernel ver directory to /lib/modules. You then need to generate an initramfs with `update-initramfs -c -k all`. Then generate your grub config again.

**Comment by fargodwe** [comment]
Ok, I did all of that.  It boots now but still no sound devices except dummy.  Do I need to do the things I tried first with the SOF things that pointed me here?  

It does appear I am running that kernel:

me@me-Aleena:~$ uname -a
Linux me-Aleena 6.5.6-stoney #1 SMP PREEMPT_DYNAMIC Fri Oct  6 13:45:37 -03 2023 x86_64 x86_64 x86_64 GNU/Linux
me@me-Aleena:~$ 

Thanks again!

**Comment by fargodwe** [comment]
Hum, somehow I lost my reply.  So, I'll do it again:

uname -a  shows I am running the kernel now.

However, still no sound devices except dummy,

**Comment by fargodwe** [comment]
I don't know if you need these or not:

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: acpd7219m98357 [acpd7219m98357], device 0: Playback da7219-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: acpd7219m98357 [acpd7219m98357], device 2: HiFi Playback HiFi-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0


lspci | grep Audio
00:01.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 15b3
00:09.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Carrizo Audio Dummy Host Bridge

**Comment by WeirdTreeThing** [comment]
aplay -l output shows that the kernel drivers did load, so this is a userspace issue. The debug script that initially failed will have more clues, I believe the package you need is `lspci`, install that then run the script.

**Comment by fargodwe** [comment]
lspci isn't a package, but I did find the problem.  The script checks to see if it exists, but it's checking in the wrong folder.  

The lspci executable is in /bin (a link to /usr/bin) but the script looks for it in /sbin and outputs the error message itself,  at least in Mint.

It's kind of funny because it looks for lsusb in the correct folder - /bin.

So, once I figured out what was going on I just commented out the if block and just left the lspci statement as standalone.

The log is attached.

Thanks!


[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13816556/debug-logs.tar.gz)

**Comment by fargodwe** [comment]
BTW - I updated the debugging.sh script to check /sbin and /bin for lspci before issuing the error.  I don't know if you want it or not but with the change is does work in Mint as well.  
[debugging.sh.txt](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13817085/debugging.sh.txt)

**Comment by WeirdTreeThing** [comment]
Yeah that script has a few issues. Thanks for getting the logs though.

**Comment by fargodwe** [comment]
I don't know if it helps in any way or not, but the card 0 internal playback devices do not show with aplay -l in Fedora 39 following the same procedures.

Thanks again!

**Comment by WeirdTreeThing** [comment]
The logs say that it failed to open a ucm file which is weird. Check if `/usr/share/alsa/ucm2/codecs/da7219/` exists on your system.

**Comment by fargodwe** [comment]
hummmm - no such file

Thanks again!

**Comment by WeirdTreeThing** [comment]
try `sudo dnf install alsa-ucm`

**Comment by fargodwe** [comment]
Tried sudo apt install alsa-ucm  - says no such package.

Went to synaptic package manager and alsa-ucm-conf and alsa-utils packages are installed.

**Comment by WeirdTreeThing** [comment]
Wait, are you on mint or fedora?

**Comment by fargodwe** [comment]
Mint 21.2   running of sdcard. Have Fedora 39 on the emmc and can boot it.  I think I posted where I tried the same things on Fedora but didn't work.

Thanks again!

**Comment by fargodwe** [comment]
The log files are from Mint.

**Comment by WeirdTreeThing** [comment]
sudo apt install alsa-ucm-conf

**Comment by fargodwe** [comment]
says alsa-ucm-conf is already the newest version (1.2.6.3-1ubuntu1.9)

**Comment by WeirdTreeThing** [comment]
Oh no wonder it doesn't work. You have a version of ucm from 2021, and the da7219 codec was a added in 2022. Fedora should work fine with the dnf command I mentioned before.

**Comment by fargodwe** [comment]
rebooting the chromebook with fedora and will let you know shortly.

thanks again!

**Comment by fargodwe** [comment]
fedora worked on the command for a little then said "package alsa-ucm-1.2.10-3.fc39.noarch is already installed"

**Comment by WeirdTreeThing** [comment]
Fedora is on the latest version so it should work.

**Comment by fargodwe** [comment]
In Fedora aplay -l only shows the 2 hdmi audio devices and they are showing as card 0.   In Mint (previous post) is shows card 0 with 2 devices then then hdmi on card 1.  Is there any way I can update ucm in mint?

**Comment by WeirdTreeThing** [comment]
Do you have the custom kernel in fedora?

**Comment by fargodwe** [comment]
I ran the same procedures in Fedora as in Mint.  However, uname -a shows Linux Fedora 6.5.6-300.fc29.x86_64 while Mint shows Linux me-Aleena 6.5.6-stoney #1 SMP PREEMPT_DYNAMIC Fri Oct 6 13:45:37 -03 2023 x86_64 x86_64 x86_64 GNU/Linux

I have no clue if that means they are the same or not.  I can always start from scratch with Fedora again if need be.  Could do the same with Mint.  Just takes time and a little fiddling to be sure Fedora on the emmc and Mint on the microsd card.

**Comment by fargodwe** [comment]
Looks like I may not have  run update-grub in Fedora.  Rebooted and did ESC and it's not showing the stoney kernel as an option even though it is in /boot.   Working on that and will let your know.

**Comment by WeirdTreeThing** [comment]
oh so the mint instructions will not work on fedora. I assume you already copied the modules, so now you need to do `sudo kernel-install add <kernel ver> <bzimage/vmlinuz>` kernel ver is the same as the modules dir name.

**Comment by fargodwe** [comment]
One of my typical dumb questions: what goes in <bzimage/vmlinuz>

**Comment by WeirdTreeThing** [comment]
the kernel image file, I forgot what exactly the name is

**Comment by fargodwe** [comment]
Ok, I'll give that a try in just a minute.  When I found no entry for the kernel in grub I had to boot any way and Fedora is doing a wonderful Windows-like thing:  Installing Updates... Do not turn off your computer and showing percentages.  Sigh.

**Comment by WeirdTreeThing** [comment]
kernel-install will create a boot entry

**Comment by fargodwe** [comment]
hum, it says kernel-install: command not found

**Comment by fargodwe** [comment]
Thank you, thank you, THANK YOU!!!!!

Have sound in speakers and headphones in Fedora!!!

First time  I've had sound on this thing in Linux.

Guess I'll have to try making everything I have for apps work in Fedora now, then install it on a microsd so I gain the larger storage.

Wish I knew a tiny bit of of all the things you must know to make this all work!

Thanks again!!

**Comment by WeirdTreeThing** [comment]
You're welcome!

**Comment by fargodwe** [comment]
> You need a custom kernel. Prebuilt kernel is at https://fs.nightcore.monster/chromebook/stoney/kernel/latest.tar.xz.

Is there anyway to see the source for that kernel as well?

Thanks

**Comment by WeirdTreeThing** [comment]
I don't remember exactly, but this should work:
Clone the latest 6.6
Revert the 2 latest commits in sound/soc/dwc
Build `SND_DESIGNWARE_I2S` and `DRM_AMDGPU` in instead of as modules
Build in these firmware files into the kernel `amdgpu/stoney_ce.bin amdgpu/stoney_me.bin amdgpu/stoney_mec.bin amdgpu/stoney_pfp.bin amdgpu/stoney_rlc.bin amdgpu/stoney_sdma.bin amdgpu/stoney_uvd.bin amdgpu/stoney_vce.bin`

**Comment by fargodwe** [comment]
I don't know if this will work since it shows as closed, but I had to re-do things and it installed the latest Fedora 40 instead of Fedora 39.  I installed the special kernel and booted it, but back to dummy output and no sound.  It is showing alsa-ucm at a newer release.  Any ideas what I've done wrong?

**Comment by adamj02090830** [comment]
> You need a custom kernel. Prebuilt kernel is at https://fs.nightcore.monster/chromebook/stoney/kernel/latest.tar.xz.

The link is down.
