### ISSUE TITLE
headphones work but no speaker out after running script on stoney.

### ISSUE THREAD

**Issue by thebestofall007** [WeirdTreeThing/chromebook-linux-audio#75]
I was looking for updates to your script and ran it again after installing the custom kernel and now I have no audio from the speakers, but the headphone out works. What configuration do I edit to fix this?

**Comment by WeirdTreeThing** [comment]
Kernel version? Logs?

**Comment by thebestofall007** [comment]
sorry about that.
I'm using kernel 6.5.6-stoney

uname -a:
6.5.6-stoney #1 SMP PREEMPT_DYNAMIC Fri Oct  6 13:45:37 -03 2023 x86_64 x86_64 x86_64 GNU/Linux



aplay -l:
**** List of PLAYBACK Hardware Devices ****
card 0: acpd7219m98357 [acpd7219m98357], device 0: Playback da7219-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: acpd7219m98357 [acpd7219m98357], device 2: HiFi Playback HiFi-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Which logs do you need?

**Comment by WeirdTreeThing** [comment]
https://docs.chrultrabook.com/docs/debugging/#acpi-and-linux-kernelspace

**Comment by thebestofall007** [comment]
OK, gotcha.
[cbmem.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13848336/cbmem.log)
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13848370/debug-logs.tar.gz)

**Comment by thebestofall007** [comment]
I just updated my system and now it works. I had to upgrade from 22.04 to 23.10.
