### ISSUE TITLE
Hp Chromebook 11a G6 ee

### ISSUE THREAD

**Issue by Floof-621** [WeirdTreeThing/chromebook-linux-audio#77]
**Describe the bug**
It was installed but didn't work at all. (I'm using ubuntu 23.10)

**Boardname**
Barla

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13928336/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Did you not see the warning that says you need a custom kernel?

**Comment by Floof-621** [comment]
No.

**Comment by WeirdTreeThing** [comment]
ubuntu makes me :(
