### ISSUE TITLE
no audio with 6.6.9 kernel on Debian bookworm or Ubuntu 22.04 

### ISSUE THREAD

**Issue by DoughMucker** [WeirdTreeThing/chromebook-linux-audio#79]
**Describe the bug**
I downloaded the 6.6.9 kernel and installed it manually. In both Debian and Ubuntu onboard audio is not listed as an option in Settings->Sound. Only headphones are listed.

I saw your commit where you changed from using nightly.link. I used that link to get the 6.6.10 kernel and it works in both distributions.

**Boardname**
Shyvana

**Logs**
FYI, In generating the logs with debugging.sh, there is a message that lspci is not found. The script looks in /sbin. I have lspci in /bin, so changed the script and ran it with success.
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13944529/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
> I saw your commit where you changed from using nightly.link. I used that link to get the 6.6.10 kernel and it works in both distributions.

I've reverted the script to use that kernel for now until upstream gets fixed.

> FYI, In generating the logs with debugging.sh, there is a message that lspci is not found. The script looks in /sbin. I have lspci in /bin, so changed the script and ran it with success.

Yeah, that script is a bit broken.

**Comment by DoughMucker** [comment]
As always, I appreciate what you do.
