### ISSUE TITLE
Sound Randomly Crashes at fedora 38 [Chromebook 14 ForWork LARS]

### ISSUE THREAD

**Issue by elKawai628** [WeirdTreeThing/chromebook-linux-audio#8]
i tried to remove `pipewire-pulseaudio` and installing pulseaudio and jack headphones work for a while until i unplug them ,if i try to plug it in again it just dont work 
here is some info
```[elkawai628@lars ~]$ pulseaudio
W: [pulseaudio] alsa-ucm.c: Path Headset Mic is not a volume or mute control
E: [pulseaudio] module-alsa-card.c: Failed to find a working profile.
E: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="3" name="platform-avs_probe_mb" card_name="alsa_card.platform-avs_probe_mb" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.
W: [pulseaudio] cli-command.c: stat('/etc/pulse/default.pa.d'): No such file or directory
N: [pulseaudio] bluez5-util.c: Could not find org.bluez.BatteryProviderManager1.RegisterBatteryProvider(), is bluetoothd started with experimental features enabled (-E flag)?
E: [pulseaudio] backend-native.c: org.bluez.ProfileManager1.RegisterProfile() failed: org.bluez.Error.NotPermitted: UUID already registered
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
W: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
```

here is more info:
`aplay -l`

```
**** List of PLAYBACK Hardware Devices ****
card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: avsnau8825 [avs_nau8825], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by WeirdTreeThing** [comment]
> E: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="3" name="platform-avs_probe_mb" card_name="alsa_card.platform-avs_probe_mb" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.

Ignore that, it doesn't matter.

Did you install the auto switcher?

**Comment by elKawai628** [comment]
yeah , and sometimes it doesn’t work

**Comment by WeirdTreeThing** [comment]
The auto switch is kinda broken right now. Try disabling it with `systemctl --user disable avs-auto-switcher.service`

**Comment by elKawai628** [comment]
audio still crashing :c , when crashes i need wait some time and itself get working , while crashed audio i hear some wierd sounds that are not loud for making me destroy my headphones

**Comment by elKawai628** [comment]
now it just did a wiiu crash sound :sob:

**Comment by WeirdTreeThing** [comment]
I've noticed some issues myself with nau8825 which I think are happening because of an old version of the topology. I updated it recently, try running the script again.

**Comment by elKawai628** [comment]
not fixed :c , and sorry for not saying that im using jack headphones

**Comment by elKawai628** [comment]
oh wait... internal speakers works good now

**Comment by WeirdTreeThing** [comment]
So just to clarify that we are talking about the same issue, if you play sound on headphones it just goes away after a few seconds and comes back after a minute or so?

**Comment by elKawai628** [comment]
yeah , something happend similar with internal speakers but it works good now

**Comment by WeirdTreeThing** [comment]
This is likely a kernel issue since I remember it working before. I'll do some of my own testing and let you know if I get it to work.

**Comment by elKawai628** [comment]
okay, take your time then!

**Comment by WeirdTreeThing** [comment]
With recent kernel updates, topology updates, and a soon to be released wireplumber config, my cave has been nearly completely stable with AVS.
