### ISSUE TITLE
intel avs module missing on debian testing 6.5.13-1

### ISSUE THREAD

**Issue by philipp023** [WeirdTreeThing/chromebook-linux-audio#80]
Hi, I got a pixelbook eve, with no sound. I wanted to fix it with your project. Unfortunately I run into this error during setup:

philipp@eve:     chromebook-linux-audio$ ./setup-audio
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing AVS
Installing topology
Installing modprobe config
Installing AVS firmware
Looks like your kernel doesn't have the avs modules. Make sure you are on at least 6.0 with avs enabled
philipp@eve:~/Downloads/chromebook-linux-audio$ uname -a
Linux eve 6.5.0-5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1 (2023-11-29) x86_64 GNU/Linux

I am on debian testing (debian stable kernel did not shutdown the machine).

How can I install the missing module in order to continue?

Thanks for your help!
Philipp

**Comment by WeirdTreeThing** [comment]
Try using the chrultrabook custom kernel https://nightly.link/chrultrabook/debian-kernel/workflows/build/main/debian-kernel.zip.

**Comment by philipp023** [comment]
Thank you for your message. I installed the Kernel. Afterwards I was able to run ./setup-audio and it is working now!
