### ISSUE TITLE
Audio still not working in Apollolake SOF, and AVS not working

### ISSUE THREAD

**Issue by apocalypt1c** [WeirdTreeThing/chromebook-linux-audio#82]
**I fixed the code (setup-audio) which was saying 'Unsupported mode: snappy'**
Line 100 error 
Prints out 'Audio installed successfully! Reboot to finish setup' but **still no audio**
┌─[✗]─[root@parrot]─[~/chromebook-linux-audio]
└──╼ #./setup-audio
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Apollolake has two audio drivers:
SOF: Stable but doesn't work with headphones.
AVS: Unstable and can cause damage to speakers but supports all audio hardware.
NOTE: Speakers are disabled on AVS as a safety precaution. (use --force-avs-install to override)Your speakers will still work on SOF though.
Which driver would you like to use? [sof/avs]: sof
Using sof
Installing SOF
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1241, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 1241 (delta 138), reused 181 (delta 65), pack-reused 976
Receiving objects: 100% (1241/1241), 212.75 KiB | 155.00 KiB/s, done.
Resolving deltas: 100% (625/625), done.
Increasing alsa headroom (fixes instability)
Audio installed successfully! Reboot to finish setup.
**Boardname**
Apollolake

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13988125/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
l33t k!d h@x0r distros are not supported

**Comment by apocalypt1c** [comment]
> l33t k!d h@x0r distros are not supported
What is all these
(((((  l3333t.....??????))))
Which distros do you mean are not supported
