### ISSUE TITLE
linux 6.6 kernel 's loop.ko module runs not normal in debian 12 

### ISSUE THREAD

**Issue by toywood** [WeirdTreeThing/chromebook-linux-audio#83]
Hi.I have download and dpkg -i the 6.6 kernel in debian 12.download link:https://tree123.org/chrultrabook/debian-kernel/linux-image-6.6.0-chrultrabook_6.6.0-2_amd64.deb . and find the module loop.ko can not work,there hasn't loop device in /dev as /dev/loop*.When i insmod loop module,then can not see loop* in /dev ,and can not see loop*,when ls /sys/block/loop*,there has no device with loop.I have try udevadm settle, and nothing changed.As i use debian-live ,the /root dir is filesystem of squashfs,it depend on loop.I can not run in xfce desktop,and stop at mount the local disk before chroot to the root-squashfs file.if have no loop,the debian live can not run on the kernel 6.6 deb package.Can you fix the loop.ko module? Thank you!

**Comment by WeirdTreeThing** [comment]
Not an audio issue
