### ISSUE TITLE
Syntax Error on ZorinOS Lite

### ISSUE THREAD

**Issue by Nightseer769** [WeirdTreeThing/chromebook-linux-audio#89]
Hi, so I just installed ZorinOS lite on a Chromebook, moving from ZorinOS Core because I found Gnome sucked up resources a lot. This is a Babymega C223N Chromebook from Asus.

I had used the audio script to fix this before when I had installed ZorinOS Core initially, but now I get a syntax error when attempting to run it here:
File "./setup-audio", line 100
    match boards[device_board]:
               ^
SyntaxError: invalid syntax

I understand ZorinOS technically uses the LTS version of Ubuntu, but as I said, this did not happen with ZorinOS core.

I have run apt update and upgrade as usual. I verified I am running Python 3.8.2.

Please let me know if there's something I'm missing. Thank you.

**Comment by WeirdTreeThing** [comment]
Not my problem if the base distro is too out of date.

**Comment by Nightseer769** [comment]
Damn, sure enough, the lite version is based on Ubuntu 20, not 22. Welp, guess I'll find some other way then.
