### ISSUE TITLE
ASoC: driver name too long (longer than 15 characters)

### ISSUE THREAD

**Issue by apandada1** [WeirdTreeThing/chromebook-linux-audio#9]
I have a Lenovo Chromebook 500e 2nd gen (PHASER360S) running Kubuntu 23.04.

I get the following entry in journalctl as well as the boot screen, because the driver name is [longer than 15 characters](https://lore.kernel.org/lkml/20230201120900.840725-1-markus.burri@mt.com/T/).

```
Jun 27 11:41:01 chromebook kernel: bxt_da7219_max98357a glk_da7219_mx98357a: ASoC: driver name too long 'sof-glkda7219max' -> 'sof-glkda7219ma'
```

Otherwise, everything works fine.

It would be great if the driver length is shortened, so that this annoying message does not show up in the boot screen.

**Comment by WeirdTreeThing** [comment]
Do you think I'm the one that writes the drivers?

**Comment by apandada1** [comment]
> Do you think I'm the one that writes the drivers?

Yes, I thought so.

In case you don't maintain the driver, what would be the appropriate place to raise the issue?

**Comment by WeirdTreeThing** [comment]
No where because it won't be changed.
