### ISSUE TITLE
plays, looks great, no actual sound

### ISSUE THREAD

**Issue by jgilmore** [WeirdTreeThing/chromebook-linux-audio#91]
**Describe the bug**
installed debian (at the recommendation of https://docs.chrultrabook.com/docs/firmware/supported-devices.html) had xubuntu on it with the same issue prior.

Sound worked fine prior to installing linux.
No sound at all after installing linux
I ran the script, it completed without errors, and claimed to have installed a new kernel.

The pulseaudio sound mixer shows that sound is playing, and going out to the second audio device (the one that's "build-in audio speaker + headphones") but no sound from speaker, and headphone jack doesn't produce sound either. Though I can see onscreen when the headphones are plugged in.

So software wise, it looks great - even has the HDMI audio out available, though I haven't tested it and it's listed as "off" which is what I'd expect.

Just no actual sound.

**Boardname**
KIP

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14074867/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Are you using pipewire or pulseaudio?

**Comment by Wildtick** [comment]
Same problem with you but instead i'm using Lubuntu (no LTS) and board name meep

**Comment by WeirdTreeThing** [comment]
Huh what? Those are two completely different boards, and two completely different issues.

**Comment by Wildtick** [comment]
man :/
