### ISSUE TITLE
AKALI360 Unknown/Unsupported

### ISSUE THREAD

**Issue by etieng** [WeirdTreeThing/chromebook-linux-audio#94]
**Boardname**
AKALI360

Hi, maybe not a bug,
The script returns :
`Unknown/Unsupported chromebook model: akali360`

Is it related to the disclaimer at docs.chrultrabook.com :
>DANGER
>Using AVS on a device with max98357a will blow your speakers. You have been warned.

Is there anyhow to enable audio on AKALI360 with any GNU/Linux setup ?

Thanks in advance

**Comment by WeirdTreeThing** [comment]
Are you running full rom or stock with rw_legacy?

> Is there anyhow to enable audio on AKALI360 with any GNU/Linux setup ?

By default you will get a warning that speakers are disabled, but headphones and mic still work. You can override that with `--force-avs-install` which will enable speakers. I have not done extensive testing but I think if you keep the volume relatively low, they wont blow up. Of course this is your decision and I am not responsible for damaged hardware.

**Comment by etieng** [comment]
Thanks for your answer.
I'm running full rom.
even with `--force-avs-install` it does return the same  `Unknown/Unsupported chromebook model: akali360`
I tried overriding the board model :
```
./setup-audio -b AKALI --enable-debug --force-avs-install
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Board name override: AKALI
Enabling AVS debugging
Done, please reboot for changes to take effect.
```
But still no sound.
And I finally understood that `--enable-debug` doesn't enable verbosity but toogle a param so i went through
```
$ ./setup-audio -b AKALI --force-avs-install
[sudo] password for titi: 
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Board name override: AKALI
Installing AVS
WARNING: Your device has max98357a and can cause permanent damage to your speakers if you set the volume too loud!
Type "I understand the risk of permanently damaging my speakers" in all caps to continue: I UNDERSTAND 
Try again
Type "I understand the risk of permanently damaging my speakers" in all caps to continue: I UNDERSTAND THE RISK OF PERMANENTLY DAMAGING MY SPEAKERS
Installing topology
Installing modprobe config
Installing AVS firmware
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1241, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 1241 (delta 138), reused 181 (delta 65), pack-reused 976
Receiving objects: 100% (1241/1241), 212.75 KiB | 3.04 MiB/s, done.
Resolving deltas: 100% (625/625), done.
Updating libasound2 (this may take some time)

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
Audio installed successfully! Reboot to finish setup.
```
And now it works.
Thank you so much for your work on theses scripts.

**Comment by WeirdTreeThing** [comment]
akali360 is weird, sometimes it can be akali360 and sometimes it can be akali 360

**Comment by WeirdTreeThing** [comment]
I added another case so it should work now
