### ISSUE TITLE
Looks like it's working but no sound

### ISSUE THREAD

**Issue by Wildtick** [WeirdTreeThing/chromebook-linux-audio#95]
Looking in my audio settings i can see that the volume is going up and down but no sound coming out from my speakers

Boardname
meep

**Logs**
down there

**Comment by Wildtick** [comment]
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14194332/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
```
[   11.497037] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:0e.0/sound/card0/input7
[   11.497122] input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:0e.0/sound/card0/input8
[   11.497192] input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:0e.0/sound/card0/input9
```
Your kernel doesn't have sof drivers?

**Comment by Wildtick** [comment]
So i'll have to install that then

**Comment by WeirdTreeThing** [comment]
No, they should be there. Maybe it isn't selecting the correct driver though. Make a file `/etc/modprobe.d/sof.conf` with this line `options snd-intel-dspcfg dsp_driver=3`.

**Comment by WeirdTreeThing** [comment]
I have no clue why it didn't use the correct driver by default.
