### ISSUE TITLE
No audio on fedora 39

### ISSUE THREAD

**Issue by xShifterx** [WeirdTreeThing/chromebook-linux-audio#97]
I install Fedora 39 on my chromebook cx5601, but there in no sound, please help fix this

**Comment by WeirdTreeThing** [comment]
I can't do anything without logs. You either didn't use the template or went out of your way to delete that part.

**Comment by xShifterx** [comment]
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing SOF
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-cs35l41.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-cs35l41.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-cs35l41.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98357a-rt5682-4ch.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-4ch.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98357a-rt5682-4ch.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98357a-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98357a-rt5682.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98360a-nau8825.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98360a-nau8825.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98360a-nau8825.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682-2way.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-2way.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682-2way.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682-4ch.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-4ch.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682-4ch.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98360a-rt5682.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98373-nau8825.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98373-nau8825.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98373-nau8825.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98390-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98390-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98390-rt5682.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-max98390-ssp2-rt5682-ssp0.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-max98390-ssp2-rt5682-ssp0.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-max98390-ssp2-rt5682-ssp0.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-nau8825.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-nau8825.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-nau8825.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-rt1019-nau8825.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-rt1019-nau8825.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-rt1019-nau8825.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-rt1019-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-rt1019-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-rt1019-rt5682.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-rt5682.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-rt711.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-rt711.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-rt711.tplg.xz
ln: failed to create symbolic link '/lib/firmware/intel/sof-tplg/sof-rpl-sdw-max98373-rt5682.tplg.xz': File exists
failed to run command: ln -s /lib/firmware/intel/sof-tplg/sof-adl-sdw-max98373-rt5682.tplg.xz /lib/firmware/intel/sof-tplg/sof-rpl-sdw-max98373-rt5682.tplg.xz
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1241, done.
remote: Counting objects: 100% (265/265), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 1241 (delta 138), reused 181 (delta 65), pack-reused 976
Receiving objects: 100% (1241/1241), 212.75 KiB | 1.62 MiB/s, done.
Resolving deltas: 100% (625/625), done.
Increasing alsa headroom (fixes instability)
Audio installed successfully! Reboot to finish setup.

**Comment by xShifterx** [comment]
i have sent the logs, please help me fix it

**Comment by ellyq** [comment]
User refused to provide logs requested by the maintainer (as per our wiki), therefore closing.
