### ISSUE TITLE
Kernel problem on debian 12

### ISSUE THREAD

**Issue by TheEpicTen** [WeirdTreeThing/chromebook-linux-audio#98]
After running the script succesfully, and restarting, I get an error message regarding the kernel not being installed. When I ran the script, it asked if I wanted to download the kernel automatically and I said Y. If I choose "Debian/GNU Linux with arm64" (i think) on boot, everything works fine, however if I choose "Debian/GNU Linux with chultrabook" (which is a new option that only appeared after running the script, it asks me to install the kernel. I am new to Linux, so any help would be appreciated, as I'm hoping to use this chromebook for work, and I really need audio for that.

(BTW, I'm using MrChromebox's firmware)

**Comment by OtterCodes101** [comment]
can you tell me the exact error?

**Comment by MrApchy** [comment]
If Secure Boot is enabled，install chultrabook Kernel will prompt for a signature error
