### ISSUE TITLE
Ubuntu 22.04.3 error "Failed to install libasound2"

### ISSUE THREAD

**Issue by twylightproto** [WeirdTreeThing/chromebook-linux-audio#99]
**Describe the bug**
libasound2 won't install

**Boardname**
Phaser360

**Logs**
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/14315000/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
use 23.10
